// data.js — STEP 12 代名詞
const QUIZ_DATA = {
  frames: [
    { id: 'f099', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 099', tagClass: 'tag-f',
      question: 'Next month I will visit ( ).',
      options: ['an American friend of me', 'an American my friend', 'a my American friend', 'an American friend of mine'], answer: 3, source: '金城学院大',
      translation: '来月私は，私のアメリカの友人を訪ねる。',
      explanation: 'myのような所有格は冠詞aと並べて名詞を修飾できない。所有代名詞mineを用いて〈a＋名詞＋of＋所有代名詞〉の形にする。' },
    { id: 'f100', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 100', tagClass: 'tag-f',
      question: 'The population of China is much larger than ( ) of Japan.',
      options: ['those', 'the one', 'that', 'it'], answer: 2, source: '九州国際大',
      translation: '中国の人口は日本の人口よりもずっと多い。',
      explanation: 'thanのあとにthe population of Japanが想定される。the populationという〈the＋名詞の単数形〉のくり返しを避けるthatを選ぶ。' },
    { id: 'f101', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 101', tagClass: 'tag-f',
      question: 'The cars we drive now are very different from ( ) we used to drive 40 years ago.',
      options: ['that', 'it', 'those', 'which'], answer: 2, source: '青山学院大',
      translation: '私たちが現在乗っている車は，40年前に乗っていた車とはかなり異なる。',
      explanation: 'the carsという〈the＋名詞の複数形〉のくり返しを避けるthose。' },
    { id: 'f102', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 102', tagClass: 'tag-f',
      question: 'You can borrow a pen if you need ( ).',
      options: ['some', 'any', 'one', 'this'], answer: 2, source: '青山学院大',
      translation: 'ペンが必要なら借りられますよ。',
      explanation: '不特定のペン（a pen）を表すので，可算名詞のくり返しを避けるone。前に出た名詞そのものを指すitとの違いに注意。' },
    { id: 'f103', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 103', tagClass: 'tag-f',
      question: 'The twins look pretty much the same; how can you tell one from ( )?',
      options: ['the another', 'each other', 'the other', 'others'], answer: 2, source: '桃山学院大',
      translation: 'その双子は本当にうりふたつですね。どうやったら2人を見分けられますか。',
      explanation: '2人のうち一方をoneで表しているので，残りの「もう1人」はthe other。' },
    { id: 'f104', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 104', tagClass: 'tag-f',
      question: "I sent New Year's postcards to Aiko and Kumi, but ( ) of them has replied so far.",
      options: ['every', 'both', 'none', 'neither'], answer: 3, source: '九州産業大',
      translation: '私はアイコとクミに年賀状を送ったが，これまでのところ2人のどちらからも返事をもらっていない。',
      explanation: '2人について「どちらも…ない」はneither。noneは3人以上。bothは肯定の意味でbutと合わない。' },
    { id: 'f105', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 105', tagClass: 'tag-f',
      question: "I can't recommend any of the three books to you, because I find ( ) interesting.",
      options: ['nobody saw any', 'both of them', 'none of them', 'neither of both'], answer: 2, source: '杏林大',
      translation: 'その3冊の本はどれもあなたにおすすめできない，というのも，私はそれらのどれもおもしろくないと思うからだ。',
      explanation: '3つ以上について「どれも…ない」はnone。' },
    { id: 'f106', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 106', tagClass: 'tag-f',
      question: 'The teacher was disappointed when ( ) her students did badly on the test.',
      options: ['the most', 'almost', 'most', 'most of'], answer: 3, source: '津田塾大',
      translation: '自分の生徒たちのほとんどがテストで悪い成績をとって，先生は落胆した。',
      explanation: '「～のほとんど」はmost of。almostは副詞で名詞を直接修飾できない。mostは〈所有格＋名詞〉を直接修飾できない。' },
    { id: 'f107', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 107', tagClass: 'tag-f',
      question: '( ) of the participants had an opportunity to speak at the meeting.',
      options: ['Almost', 'Nobody', 'Each', 'Every'], answer: 2, source: '近畿大',
      translation: '参加者のそれぞれに会議で発言する機会があった。',
      explanation: 'of the participantsが続く。3人以上について「それぞれ」はEach。Everyはof ～を続けられない。' },
    { id: 'f108', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 108', tagClass: 'tag-f',
      question: 'I had ( ) to do with the accident.',
      options: ['neither', 'never', 'nothing', 'not'], answer: 2, source: '金城学院大',
      translation: '私はその事故とは何の関係もない。',
      explanation: 'have nothing to do with ～で「～と何の関係もない」。' },
    { id: 'f109', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 109', tagClass: 'tag-f',
      question: 'The parade is held once ( ) two years.',
      options: ['on', 'at', 'every', 'for'], answer: 2, source: '南山大',
      translation: 'パレードは2年に1度行われる。',
      explanation: '〈every＋基数詞＋複数名詞〉で「～ごとに」。' },
    { id: 'f110', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 110', tagClass: 'tag-f',
      question: 'Would you blame ( ) if you were in my situation?',
      options: ['you', 'myself', 'yourself', 'I'], answer: 2, source: 'センター試験',
      translation: 'もしあなたが私の立場なら，あなたは自分を責めるでしょうか。',
      explanation: 'blameの目的語が主語youと同じなので再帰代名詞yourself。目的語が「私」ならmeとなるはず。' }
  ],
  exA: [
    { id: 'a01', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 01', tagClass: 'tag-a',
      question: 'Please take ( ) with you and tell me what you think of them tomorrow.',
      options: ['these letters of his', 'his letters of these', 'his these letters', 'these his letters'], answer: 0, source: '東海大',
      translation: 'これらの彼の手紙を持って行ってください，そして明日それらについてどう思うか私に教えてください。',
      explanation: 'hisのような所有格はtheseと並べて名詞を修飾できない。〈these＋名詞＋of＋所有代名詞〉。' },
    { id: 'a02', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 02', tagClass: 'tag-a',
      question: 'The population of Fukuoka City is larger than ( ) of Kitakyushu City.',
      options: ['those', 'one', 'the ones', 'that'], answer: 3, source: '九州産業大',
      translation: '福岡市の人口は北九州市の人口よりも多い。',
      explanation: 'the populationという〈the＋名詞の単数形〉のくり返しを避けるthat。' },
    { id: 'a03', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 03', tagClass: 'tag-a',
      question: 'Our rules are quite different from ( ) of other clubs.',
      options: ['they', 'that', 'those', 'them'], answer: 2, source: '芝浦工業大',
      translation: '私たちの規則は，他のクラブの規則とはかなり違う。',
      explanation: 'the rulesという〈the＋名詞の複数形〉のくり返しを避けるthose。' },
    { id: 'a04', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 04', tagClass: 'tag-a',
      question: 'My father bought a computer yesterday. I already ( ).',
      options: ['bought it', 'have one', 'have it', 'bought'], answer: 1, source: '東北学院大',
      translation: '私の父は昨日コンピュータを買った。私はコンピュータをすでに持っている。',
      explanation: '「（父が買ったのとは別の）コンピュータをすでに持っている」。itを用いると父の買ったコンピュータを指すことになる。' },
    { id: 'a05', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 05', tagClass: 'tag-a',
      question: "Susie has got some yellow socks, but I've got ( ).",
      options: ['blue them', 'blue ones', 'ones blue', 'them blue'], answer: 1, source: 'センター試験',
      translation: 'スージーは黄色の靴下を持っているが，私は青い靴下を持っている。',
      explanation: 'blue socksを表す。可算名詞のくり返しを避けるoneの複数形ones。' },
    { id: 'a06', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 06', tagClass: 'tag-a',
      question: '"What did the doctor say?" "He told me to go to bed and drink plenty of fluids. He also told me to take these pills ( ) four hours."',
      options: ['another', 'the other', 'some', 'every'], answer: 3, source: '法政大',
      translation: '「お医者さんは何と言ったのですか」「彼は私に，寝て水分をたっぷり飲むように言いました。彼はまた私に，4時間ごとにこれらの薬を飲むように言いました」',
      explanation: '〈every＋基数詞＋複数名詞〉で「～ごとに」。every four hoursで「4時間ごとに」。' },
    { id: 'a07', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 07', tagClass: 'tag-a',
      question: 'I have two daughters. One daughter is a college student and ( ) one works in a bank.',
      options: ['next', 'either', 'second', 'the other'], answer: 3, source: '昭和大',
      translation: '私には2人の娘がいる。娘の1人は大学生で，もう1人は銀行に勤めている。',
      explanation: '2人のうち一方をoneで表しているので，残りの「もう1人」はthe other。' },
    { id: 'a08', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 08', tagClass: 'tag-a',
      question: 'This T-shirt is a little small for me. Please show me ( ).',
      options: ['one', 'some', 'another', 'other'], answer: 2, source: '椙山女学園大',
      translation: 'このTシャツは私には少し小さいです。別のものを見せてください。',
      explanation: '不特定多数の中の「別の1つ」はanother。' },
    { id: 'a09', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 09', tagClass: 'tag-a',
      question: 'Some of the cars were blue, ( ) were red, and the rest were white.',
      options: ['all the others', 'the other', 'others', 'another'], answer: 2, source: '明治大',
      translation: '車の何台かは青で，別の何台かは赤で，そして残りは白だった。',
      explanation: '他の不特定多数を指す「他の複数の物」others。' },
    { id: 'a10', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 10', tagClass: 'tag-a',
      question: 'He has three sisters: one is a college student, and ( ) are office workers.',
      options: ['rest', 'other', 'another', 'the others'], answer: 3, source: '東海大',
      translation: '彼には3人の姉妹がいる。1人は大学生で，他の姉妹は会社員だ。',
      explanation: '1人を除いた他の全員を指す「残りの複数の人」the others。' },
    { id: 'a11', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 11', tagClass: 'tag-a',
      question: 'To say it is one thing. To do it is quite ( ).',
      options: ['the other', 'another', 'other', 'the another'], answer: 1, source: '名古屋学院大',
      translation: '言うことと，それをすることは，まったく別物だ。',
      explanation: 'A is one thing, B is another. で「AとBは別物だ」。' },
    { id: 'a12', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 12', tagClass: 'tag-a',
      question: '"Why didn\'t they go to the movies?" "( ) of them had any money."',
      options: ['Any', 'Some', 'None', 'All'], answer: 2, source: '広島工業大',
      translation: '「どうして彼らは映画に行かなかったの」「彼らのだれもお金を持っていなかったんだ」',
      explanation: '3人以上について「だれも…ない」はnone。' },
    { id: 'a13', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 13', tagClass: 'tag-a',
      question: 'This shirt is too big and the other is too small. ( ) fits me.',
      options: ['Neither', 'Either', 'Both', 'It'], answer: 0, source: '四天王寺国際仏教短大',
      translation: 'このシャツは大きすぎて，もう1枚のほうは小さすぎる。どちらも私に合わない。',
      explanation: '2枚について「どちらも…ない」はNeither。' },
    { id: 'a14', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 14', tagClass: 'tag-a',
      question: "Kenji has two brothers, but he is not on speaking terms with them. In other words, he doesn't talk to ( ) of them.",
      options: ['both', 'neither', 'which', 'either'], answer: 3, source: '名古屋工業大',
      translation: 'ケンジには兄弟が2人いるが，彼らとは口もきかない間柄だ。つまり，彼らのどちらとも話をしないということだ。',
      explanation: 'be not on speaking terms with ～は「～とは口もきかない間柄である」。not ... eitherの形にする。neitherは否定語doesn\'tがあるので不可。' },
    { id: 'a15', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 15', tagClass: 'tag-a',
      question: '( ) students are living away from their home.',
      options: ['Most of the', 'Almost', 'Most of', 'The most of'], answer: 0, source: '愛知県立大',
      translation: '学生のほとんどは実家から離れて住んでいる。',
      explanation: '「学生のほとんど」はmost studentsまたはmost of the students。' },
    { id: 'a16', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 16', tagClass: 'tag-a',
      question: 'I keep nine hamsters in my room, and ( ) of them has a name.',
      options: ['each', 'either', 'all', 'every'], answer: 0, source: '近畿大',
      translation: '私は自分の部屋に9匹のハムスターを飼っていて，それらのそれぞれに名前がある。',
      explanation: 'of themが続く。allなら動詞がhaveとなるはず。everyはof ～を続けられない。' },
    { id: 'a17', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 17', tagClass: 'tag-a',
      question: 'In Japan ( ) people go on to senior high school after finishing junior high school.',
      options: ['almost', 'most of', 'almost of', 'most'], answer: 3, source: 'センター試験',
      translation: '日本では中学卒業後はほとんどの人々が高校に進学する。',
      explanation: 'almostは副詞で名詞を直接修飾できない。most ofは〈the＋名詞〉など特定の名詞が必要。' },
    { id: 'a18', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 18', tagClass: 'tag-a',
      question: 'At the breakfast meeting today, ( ) the employees were present.',
      options: ['nearly', 'most', 'almost', 'almost all'], answer: 3, source: '東海大',
      translation: '今日の朝食会には，社員のほぼ全員が出席していた。',
      explanation: '空所の直後に〈the＋名詞〉。「～のほぼ全員」almost all。' },
    { id: 'a19', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 19', tagClass: 'tag-a',
      question: 'Your answer has ( ) to do with my question.',
      options: ['none', 'not', 'nothing', 'no'], answer: 2, source: '福岡大',
      translation: 'あなたの答えは私の質問とは何の関係もない。',
      explanation: 'have nothing to do with ～で「～と何の関係もない」。' },
    { id: 'a20', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 20', tagClass: 'tag-a',
      question: '( ) who want to attend the workshop next week should contact Laura.',
      options: ['Some', 'Everyone', 'Person', 'Those'], answer: 3, source: '金沢工業大',
      translation: '来週の講習会に参加したい人はローラに連絡してください。',
      explanation: 'those who ...で「…する人々」。whoが導く節の動詞がwantなので，単数扱いのEveryoneやPersonは不可。' },
    { id: 'a21', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 21', tagClass: 'tag-a',
      question: 'Although Professor Snyder is one of the leading researchers in economics, he does not consider ( ) to be a great teacher.',
      options: ['himself', 'his', 'he', 'him'], answer: 0, source: '神奈川大',
      translation: 'スナイダー教授は経済学で指導的な研究者の1人であるけれども，彼は自分を優れた教師であるとは考えていない。',
      explanation: 'considerの目的語が主語heと同じ人物なので再帰代名詞himself。' },
    { id: 'a22', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 22', tagClass: 'tag-a',
      question: 'I tried to do my homework, but I found ( ) was something wrong with my computer.',
      options: ['then', 'there', 'it', 'that'], answer: 1, source: '大東文化大',
      translation: '私は宿題をしようとしたのだが，私のコンピュータのどこか調子が悪いことに気づいた。',
      explanation: 'there is something wrong with ～で「～はどこか調子が悪い」。' },
    { id: 'a23', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 23', tagClass: 'tag-a',
      question: '"Who did you go to the movie with?" "No one. I went ( )."',
      options: ['by nobody', 'by myself', 'with anyone', 'with him'], answer: 1, source: '駒澤大',
      translation: '「だれと一緒に映画に行ったのですか」「だれとも行きませんでした。私は1人で行きました」',
      explanation: 'by oneselfで「1人で」。主語がIなのでby myself。' },
    { id: 'a24', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 24', tagClass: 'tag-a',
      question: 'I think my speech went down reasonably well. How did ( ) go?',
      options: ["you're", 'your', 'yours', 'yourself'], answer: 2, source: '駿河台大',
      translation: '私のスピーチはまあまあ受けがよかったと思う。あなたのはどうでしたか。',
      explanation: 'your speechのくり返しを避ける所有代名詞yours。所有格yourは単独では用いられない。' }
  ],
  exB: [
    { id: 'b01', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 01', tagClass: 'tag-b',
      question: "If I ask my co-workers whether ①they'd mind meeting on ②a Sunday, I'm sure ③almost of them will say it's ④out of the question.",
      options: ['①', '②', '③', '④'], answer: 2, source: '立命館大',
      spans: ["they'd mind meeting on", 'a Sunday', 'almost', 'out of the question'],
      correction: '③ almost → most', corrected: "If I ask my co-workers whether they'd mind meeting on a Sunday, I'm sure most of them will say it's out of the question.",
      translation: '同僚たちに日曜日に会合を開いてもかまわないかどうかたずねたなら，おそらく彼らのほとんどがそれは問題外だと言うだろう。',
      explanation: 'almostは副詞でalmost of ～の形をとれない。mostにしてmost of ～「～のほとんど」の形にする。' },
    { id: 'b02', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 02', tagClass: 'tag-b',
      question: '①Due to the failure of the communication system, ②no one of us was able ③to broadcast ④the first pictures of the disaster.',
      options: ['①', '②', '③', '④'], answer: 1, source: '関西学院大',
      spans: ['Due to', 'no one of us', 'to broadcast', 'the first pictures'],
      correction: '② no one of us → none of us', corrected: 'Due to the failure of the communication system, none of us was able to broadcast the first pictures of the disaster.',
      translation: '通信システムの障害のために，私たちのだれもその災害の最初の映像を放送することができなかった。',
      explanation: 'no oneはあとにof ～を続けられない。' },
    { id: 'b03', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 03', tagClass: 'tag-b',
      question: '①Continuing to release greenhouse ②gases at current rates ③would yield much more severe consequences during this century than ④that we saw in the previous one.',
      options: ['①', '②', '③', '④'], answer: 3, source: '中央大',
      spans: ['Continuing to release greenhouse', 'gases at current rates', 'would yield', 'that'],
      correction: '④ that → those', corrected: 'Continuing to release greenhouse gases at current rates would yield much more severe consequences during this century than those we saw in the previous one.',
      translation: '現在の割合で温室効果ガスを放出し続けると，今世紀中には私たちが前世紀に経験したよりもずっと深刻な結果が生じるだろう。',
      explanation: 'the consequencesという〈the＋名詞の複数形〉のくり返しを避けるthose。' },
    { id: 'b04', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 04', tagClass: 'tag-b',
      question: 'If you ①come across ②unfamiliar words, you should ③look up them in ④the dictionary.',
      options: ['①', '②', '③', '④'], answer: 2, source: '静岡大',
      spans: ['come across', 'unfamiliar words', 'look up them', 'the dictionary'],
      correction: '③ look up them → look them up', corrected: 'If you come across unfamiliar words, you should look them up in the dictionary.',
      translation: 'もし知らない単語に出会ったら，辞書でそれらを調べるべきだ。',
      explanation: 'look up ～は〈動詞＋副詞〉型。目的語が代名詞ならlook ～ upの語順。' },
    { id: 'b05', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 05', tagClass: 'tag-b',
      question: '①The dog is one of the two ②most ubiquitous and ③popular domestic animals in the world; the cat is ④another.',
      options: ['①', '②', '③', '④'], answer: 3, source: '東京理科大',
      spans: ['The dog is one of the two', 'most ubiquitous and', 'popular domestic animals', 'another'],
      correction: '④ another → the other', corrected: 'The dog is one of the two most ubiquitous and popular domestic animals in the world; the cat is the other.',
      translation: '犬は，世界で2種の最もありふれて人気のある家畜のうちの1種である。猫が残りの1種である。',
      explanation: '2つのうち片方をoneで表しているので，残りはthe other。' },
    { id: 'b06', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 06', tagClass: 'tag-b',
      question: 'Each country must ①accept the responsibility ②for the well-being of ③their citizens and for the equal treatment of its ④minorities.',
      options: ['①', '②', '③', '④'], answer: 2, source: '高崎経済大',
      spans: ['accept the responsibility', 'for the well-being of', 'their', 'minorities'],
      correction: '③ their → its', corrected: 'Each country must accept the responsibility for the well-being of its citizens and for the equal treatment of its minorities.',
      translation: '各国は自国の国民の福利と少数派の平等な扱いに責任をもたなければならない。',
      explanation: '〈Each＋単数名詞〉は単数扱い。あとのits minoritiesとも呼応。' },
    { id: 'b07', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 07', tagClass: 'tag-b',
      question: '①In this area, seals are ②a protected species, but you will find ③its meat ④on the menu in local restaurants.',
      options: ['①', '②', '③', '④'], answer: 2, source: '立教大',
      spans: ['In this area', 'a protected species', 'its', 'on the menu'],
      correction: '③ its → their', corrected: 'In this area, seals are a protected species, but you will find their meat on the menu in local restaurants.',
      translation: 'この地域ではアザラシは保護種だが，地元のレストランではその肉がメニューに載っているのが見つかるだろう。',
      explanation: 'itsは複数形のsealsを指すのでtheir。' }
  ],
  exC: [
    { id: 'c01', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 01', tagClass: 'tag-c',
      japanese: '私はその事件に関係がない。', prefix: 'I', suffix: 'the affair.',
      words: ['do', 'nothing', 'with', 'to', 'have'], note: null, source: '東海学院大',
      answer: 'I have nothing to do with the affair.',
      explanation: 'have nothing to do with ～で「～と何の関係もない」。' },
    { id: 'c02', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 02', tagClass: 'tag-c',
      japanese: '彼女はお金のことに不平ばかり言っている。［1語不要］', prefix: 'She', suffix: '.',
      words: ['about', 'but', 'complain', 'only', 'does', 'money', 'nothing'], note: '1語不要', source: '東京理科大',
      answer: 'She does nothing but complain about money.',
      explanation: 'do nothing but doで「…してばかりいる」。butのあとは動詞の原形。onlyが不要。' },
    { id: 'c03', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 03', tagClass: 'tag-c',
      japanese: '', prefix: 'People of all cultures', suffix: '.',
      words: ['privacy at some times', 'seek', 'companionship at others', 'and'], note: null, source: '青山学院大',
      translation: 'あらゆる文化の人々が，ある時にはプライバシーを求め，また別の時には交流を求める。',
      answer: 'People of all cultures seek privacy at some times and companionship at others.',
      explanation: 'at some timesとat others（＝other times）が呼応。' },
    { id: 'c04', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 04', tagClass: 'tag-c',
      japanese: '', prefix: 'Do you remember where that bicycle shop was? Something', suffix: 'I bought at the sale.',
      words: ['gone', 'has', 'the', 'bicycle', 'with', 'wrong'], note: null, source: 'センター試験',
      translation: 'あの自転車店がどこにあったか覚えていますか。私がセールで買った自転車はどこか調子が悪くなってしまいました。',
      answer: 'Do you remember where that bicycle shop was? Something has gone wrong with the bicycle I bought at the sale.',
      explanation: 'Something is wrong with ～で「～はどこか調子が悪い」。ここではisをhas goneに変える。' },
    { id: 'c05', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 05', tagClass: 'tag-c',
      japanese: '', prefix: 'Those', suffix: 'if they know how to use a library.',
      words: ['information', 'to find it', 'who need', 'be able', 'will usually'], note: null, source: 'センター試験',
      translation: '情報が必要な人々は，図書館の利用のしかたを知っていれば，たいていそれを見つけることができるだろう。',
      answer: 'Those who need information will usually be able to find it if they know how to use a library.',
      explanation: 'those who ...で「…する人々」。Thoseのあとに関係代名詞節who need informationを続け，述語動詞はwill usually be able to findとする。' }
  ]
};

const EIGO_SENTENCES = [];
