// data.js — STEP 08 動詞の語法
const QUIZ_DATA = {
  frames: [
    { id: 'f063', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 063', tagClass: 'tag-f',
      question: 'I bought this T-shirt for my baby. It feels so ( ).',
      options: ['like soft', 'soft', 'softly', 'to be softly'], answer: 1, source: '近畿大',
      translation: '私は赤ちゃんのためにこのTシャツを買った。とても柔らかい手ざわりだ。',
      explanation: 'feelは「～の感じがする」の意味では〈feel＋形容詞〉の第2文型をとる。副詞softlyは補語になれない。' },
    { id: 'f064', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 064', tagClass: 'tag-f',
      question: 'They ( ) the serious problem of rich families.',
      options: ['discussed of', 'discussed', 'discussed about', 'discussed with'], answer: 1, source: '神戸山手大',
      translation: '彼らは裕福な家庭の深刻な問題について議論した。',
      explanation: 'discussは「～について議論する」の意味の他動詞。前置詞about／of／withは不要。' },
    { id: 'f065', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 065', tagClass: 'tag-f',
      question: 'I cannot ( ) you how lucky I was to have a chance to see that painting.',
      options: ['tell', 'yell', 'speak', 'say'], answer: 0, source: '星薬科大',
      translation: 'あの絵を見る機会があって自分がどれほど幸運だったか，あなたに言い表せない。',
      explanation: '〈tell＋人＋事〉の形をとれるのはtell。say／speakは直後に「人」を目的語にとれない。' },
    { id: 'f066', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 066', tagClass: 'tag-f',
      question: 'Will you please explain ( ) once again?',
      options: ['the point us', 'us the point', 'the point to us', 'us about the point'], answer: 2, source: '東京工芸大',
      translation: 'もう一度その点を私たちに説明していただけますか。',
      explanation: 'explainは〈explain＋事＋to＋人〉の語順。〈explain＋人＋事〉の第4文型は不可。' },
    { id: 'f067', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 067', tagClass: 'tag-f',
      question: 'He ( ) on the sofa and quickly fell asleep.',
      options: ['lay', 'lied', 'lain', 'laid'], answer: 0, source: '茨城キリスト教大',
      translation: '彼はソファーに横になり，すぐに眠ってしまった。',
      explanation: '自動詞lie（横になる）の過去形lay。lie-lay-lain。他動詞lay（置く）の過去形laidと混同しない。' },
    { id: 'f068', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 068', tagClass: 'tag-f',
      question: 'Drinking and smoking will ( ) you great harm.',
      options: ['have', 'be', 'help', 'do'], answer: 3, source: 'つくば国際大',
      translation: '飲酒と喫煙はあなたに大きな害を与えるだろう。',
      explanation: '〈do＋人＋harm〉で「人に害を与える」。do ～ goodなら「人のためになる」。' },
    { id: 'f069', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 069', tagClass: 'tag-f',
      question: 'Smoking robbed him ( ) his health.',
      options: ['to', 'of', 'with', 'for'], answer: 1, source: '亜細亜大',
      translation: '喫煙が彼から健康を奪った。',
      explanation: '〈rob＋人＋of＋物〉で「人から物を奪う」。奪う対象はofのあとに置く。' },
    { id: 'f070', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 070', tagClass: 'tag-f',
      question: 'The story that John told us reminded me ( ) another painful experience.',
      options: ['with', 'of', 'to', 'from'], answer: 1, source: '杏林大',
      translation: 'ジョンが私たちに話した話は，私にもう1つのつらい経験を思い出させた。',
      explanation: '〈remind＋人＋of＋事〉で「人に事を思い出させる」。' },
    { id: 'f071', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 071', tagClass: 'tag-f',
      question: 'The horrible snowstorm discouraged us ( ) out.',
      options: ['from go', 'to go', 'from going', 'to going'], answer: 2, source: '南山大',
      translation: 'ひどい吹雪のせいで私たちは外出する気をなくした。',
      explanation: '〈discourage＋人＋from doing〉で「人に…する気をなくさせる」。fromのあとは動名詞。' },
    { id: 'f072', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 072', tagClass: 'tag-f',
      question: 'She had her hair ( ) for the dance.',
      options: ['to be cut', 'cutting', 'to cut', 'cut'], answer: 3, source: '法政大',
      translation: '彼女はダンスパーティーのために髪を切ってもらった。',
      explanation: '〈have＋物＋過去分詞〉で「物を…してもらう」。her hairは「切られる」側なので過去分詞cut。' }
  ],
  exA: [
    { id: 'a01', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 01', tagClass: 'tag-a',
      question: "Don't climb up that ladder! It doesn't look ( ).",
      options: ['safe', 'safely', 'in safety', 'dangerously'], answer: 0, source: '福岡大',
      translation: 'そのはしごを登ってはいけない。安全そうには見えない。',
      explanation: 'look「～に見える」は〈look＋形容詞〉の第2文型。副詞は補語にならない。' },
    { id: 'a02', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 02', tagClass: 'tag-a',
      question: 'Two students are going to ( ) the topic.',
      options: ['discuss', 'discuss about', 'discuss on', 'discuss of'], answer: 0, source: '甲南大',
      translation: '2人の学生がそのテーマについて議論する予定だ。',
      explanation: 'discussは他動詞なので前置詞は不要。' },
    { id: 'a03', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 03', tagClass: 'tag-a',
      question: 'Kevin and Julie got ( ) in Hawaii.',
      options: ['marry', 'marriage', 'marrying', 'married'], answer: 3, source: '南山大',
      translation: 'ケビンとジュリーはハワイで結婚した。',
      explanation: 'get marriedで「結婚する」。marryは他動詞でmarry with ～とは言わない。' },
    { id: 'a04', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 04', tagClass: 'tag-a',
      question: 'When did you ( ) that university?',
      options: ['graduate', 'graduate at', 'graduate from', 'graduate of'], answer: 2, source: '神奈川大',
      translation: 'あなたはいつその大学を卒業したのですか。',
      explanation: 'graduate from ～で「～を卒業する」。graduateは自動詞なのでfromが必要。' },
    { id: 'a05', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 05', tagClass: 'tag-a',
      question: 'The first typhoon is ( ) the Philippines right now.',
      options: ['approaching', 'coming', 'going', 'nearness'], answer: 0, source: '東京工芸大',
      translation: '最初の台風が今まさにフィリピンに接近している。',
      explanation: 'approachは「～に近づく」の他動詞。come／goは目的語を直接とれない。' },
    { id: 'a06', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 06', tagClass: 'tag-a',
      question: 'She can ( ) me at this number.',
      options: ['talk', 'take', 'arrive', 'reach'], answer: 3, source: '駒澤大',
      translation: '彼女はこの番号で私に連絡をとることができます。',
      explanation: 'reachは「～に連絡がつく，到達する」の他動詞。arriveは自動詞でatが必要。' },
    { id: 'a07', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 07', tagClass: 'tag-a',
      question: 'He ( ) the room saying hello.',
      options: ['appeared', 'came', 'emerged', 'entered'], answer: 3, source: '日本大',
      translation: '彼はあいさつをしながら部屋に入ってきた。',
      explanation: 'enterは「～に入る」の他動詞。come／appear／emergeは目的語を直接とれない。' },
    { id: 'a08', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 08', tagClass: 'tag-a',
      question: 'He was so worn out that he just ( ) down and slept.',
      options: ['had lain', 'laid', 'lay', 'lied'], answer: 2, source: '北里大',
      translation: '彼はとても疲れきっていたので，ただ横になって眠った。',
      explanation: 'lie down「横になる」の過去形lay。liedはlie「うそをつく」の過去形。' },
    { id: 'a09', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 09', tagClass: 'tag-a',
      question: 'These books ( ) young people great harm.',
      options: ['do', 'make', 'have', 'give'], answer: 0, source: '関西学院大',
      translation: 'これらの本は若者に大きな害を与える。',
      explanation: '〈do＋人＋harm〉で「人に害を与える」。' },
    { id: 'a10', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 10', tagClass: 'tag-a',
      question: 'The pilot ( ) the landing was delayed.',
      options: ['explained to us what', 'explained us why', 'explained to us why', 'explained us of why'], answer: 2, source: '同志社大',
      translation: 'パイロットは着陸が遅れた理由を私たちに説明した。',
      explanation: 'explainは〈explain＋to＋人＋事〉の語順。あとに完全な文が続くのでwhy。' },
    { id: 'a11', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 11', tagClass: 'tag-a',
      question: 'Would you please ( ) me where the subway station is?',
      options: ['say', 'explain', 'tell', 'speak'], answer: 2, source: '名城大',
      translation: '地下鉄の駅がどこにあるか教えていただけますか。',
      explanation: '〈tell＋人＋事〉の第4文型をとれるのはtell。explainは人を直接目的語にできない。' },
    { id: 'a12', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 12', tagClass: 'tag-a',
      question: 'The newspaper ( ) it was going to rain.',
      options: ['said', 'spoke', 'talked', 'told'], answer: 0, source: '関西学院大',
      translation: '新聞には雨が降りそうだと書いてあった。',
      explanation: '新聞・手紙などを主語にして「～と書いてある」はsay。that節を直接とれる。' },
    { id: 'a13', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 13', tagClass: 'tag-a',
      question: 'Jennifer ( ) her own work experience in India.',
      options: ['spoke', 'talked about', 'said', 'told to'], answer: 1, source: '甲南大',
      translation: 'ジェニファーはインドでの自分自身の仕事の経験について話した。',
      explanation: 'talkは自動詞なので「～について話す」はtalk about ～。' },
    { id: 'a14', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 14', tagClass: 'tag-a',
      question: 'Sitting there like that, you ( ) me of my mother.',
      options: ['remind', 'remember', 'recollect', 'recall'], answer: 0, source: '摂南大',
      translation: 'そんなふうにそこに座っていると，あなたは私に母を思い出させる。',
      explanation: '〈remind＋人＋of ～〉の形をとるのはremind。remember／recallは「自分で思い出す」。' },
    { id: 'a15', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 15', tagClass: 'tag-a',
      question: 'Kate ( ) of all the money she had with her.',
      options: ['robbed', 'was robbed', 'deprived', 'had deprived'], answer: 1, source: '関西学院大',
      translation: 'ケイトは持っていたお金を全部奪われた。',
      explanation: '〈rob＋人＋of＋物〉の受動態。ケイトは「奪われる」側なのでwas robbed。' },
    { id: 'a16', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 16', tagClass: 'tag-a',
      question: "My parents are trying to ( ) me from moving to London, but I'm planning to go anyway.",
      options: ['discourage', 'recall', 'observe', 'relieve'], answer: 0, source: '獨協大',
      translation: '両親は私がロンドンに引っ越すのをやめさせようとしているが，私はいずれにせよ行くつもりだ。',
      explanation: '〈discourage＋人＋from doing〉で「人に…する気をなくさせる」。' },
    { id: 'a17', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 17', tagClass: 'tag-a',
      question: 'A new law ( ) people from drinking in the park.',
      options: ['permits', 'prohibits', 'refuses', 'exhibits'], answer: 1, source: '甲南大',
      translation: '新しい法律は公園での飲酒を禁止している。',
      explanation: '〈prohibit＋人＋from doing〉で「人が…するのを禁じる」。' },
    { id: 'a18', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 18', tagClass: 'tag-a',
      question: 'Prior research has shown that the key to building muscles ( ) in a healthy diet.',
      options: ['lays', 'lies', 'lying', 'will lay'], answer: 1, source: '立命館大',
      translation: '先行研究は，筋肉をつける鍵は健康的な食事にあることを示している。',
      explanation: 'lie in ～で「～にある」。自動詞lieなので目的語をとる他動詞layは不可。' },
    { id: 'a19', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 19', tagClass: 'tag-a',
      question: 'Because of the noise, Tom had to ( ) his voice to be heard.',
      options: ['rise', 'stand', 'heighten', 'raise'], answer: 3, source: '芝浦工業大',
      translation: '騒音のせいで，トムは声が聞こえるように声を張り上げなければならなかった。',
      explanation: 'his voiceという目的語があるので他動詞raise「～を上げる」。riseは自動詞。' },
    { id: 'a20', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 20', tagClass: 'tag-a',
      question: 'The number of cases of the disease continued to ( ).',
      options: ['raise', 'rise', 'raising', 'rising'], answer: 1, source: '亜細亜大',
      translation: 'その病気の症例数は増え続けた。',
      explanation: '目的語がないので自動詞rise「増える，上がる」。continue to doなので原形。' },
    { id: 'a21', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 21', tagClass: 'tag-a',
      question: 'He had his bicycle ( ) in front of that convenience store.',
      options: ['stealing', 'steal', 'stolen', 'be stolen'], answer: 2, source: '追手門学院大',
      translation: '彼はあのコンビニの前で自転車を盗まれた。',
      explanation: '〈have＋物＋過去分詞〉で「物を…される」の被害の意味。' }
  ],
  exB: [
    { id: 'b01', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 01', tagClass: 'tag-b',
      question: '①After ②attending the meeting yesterday, he ③seriously ④talked the issue.',
      options: ['①', '②', '③', '④'], answer: 3, source: '明海大',
      spans: ['After', 'attending', 'seriously', 'talked'],
      correction: '④ talked → discussed', corrected: 'After attending the meeting yesterday, he seriously discussed the issue.',
      translation: '昨日その会議に出席したあと，彼はその問題について真剣に議論した。',
      explanation: 'talkは自動詞なのでthe issueを直接目的語にとれない。他動詞discussにする（talked about the issueでも可）。' },
    { id: 'b02', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 02', tagClass: 'tag-b',
      question: 'The rays ①from the sun penetrate the atmosphere, ②while the ③greenhouse gases prevent heat ④to escape into space.',
      options: ['①', '②', '③', '④'], answer: 3, source: '関西学院大',
      spans: ['from', 'while', 'greenhouse gases', 'to escape'],
      correction: '④ to escape → from escaping', corrected: 'The rays from the sun penetrate the atmosphere, while the greenhouse gases prevent heat from escaping into space.',
      translation: '太陽光線は大気を透過するが，温室効果ガスは熱が宇宙空間へ逃げるのを妨げる。',
      explanation: '〈prevent＋O＋from doing〉で「Oが…するのを妨げる」。prevent ～ to doの形はない。' },
    { id: 'b03', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 03', tagClass: 'tag-b',
      question: 'The author is going to ①discuss to the implications of mobile Internet access for libraries, ②which would allow innovation in ③their ④services.',
      options: ['①', '②', '③', '④'], answer: 0, source: '明治学院大',
      spans: ['discuss to', 'which', 'their', 'services'],
      correction: '① discuss to → discuss', corrected: 'The author is going to discuss the implications of mobile Internet access for libraries, which would allow innovation in their services.',
      translation: '著者は，図書館にとってのモバイルインターネット接続の影響について論じるつもりだ。それは図書館のサービスに革新をもたらすだろう。',
      explanation: 'discussは他動詞なので前置詞toは不要。' },
    { id: 'b04', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 04', tagClass: 'tag-b',
      question: 'When we visited ①her office for a regular check-up, Dr. Dixon told my mom ②to go to the hospital ③to have her stomach ④examine.',
      options: ['①', '②', '③', '④'], answer: 3, source: '杏林大',
      spans: ['her office', 'to go', 'to have', 'examine'],
      correction: '④ examine → examined', corrected: 'When we visited her office for a regular check-up, Dr. Dixon told my mom to go to the hospital to have her stomach examined.',
      translation: '定期検診で診察を受けに行ったとき，ディクソン先生は母に病院へ行って胃を検査してもらうように言った。',
      explanation: '〈have＋物＋過去分詞〉で「物を…してもらう」。her stomachは「検査される」側なのでexamined。' },
    { id: 'b05', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 05', tagClass: 'tag-b',
      question: '①Owing to the appearance of competitors in the neighborhood, we will have to ②give up our plan to ③rise the price by twenty ④percent.',
      options: ['①', '②', '③', '④'], answer: 2, source: '福岡大',
      spans: ['Owing to', 'give up', 'rise', 'percent'],
      correction: '③ rise → raise', corrected: 'Owing to the appearance of competitors in the neighborhood, we will have to give up our plan to raise the price by twenty percent.',
      translation: '近所に競合店が現れたため，私たちは値段を20パーセント上げる計画をあきらめなければならないだろう。',
      explanation: 'the priceという目的語があるので他動詞raise。riseは自動詞で目的語をとれない。' }
  ],
  exC: [
    { id: 'c01', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 01', tagClass: 'tag-c',
      japanese: 'あなたの話を聞いて，数年前に私にも同じようなことがあったのを思い出した。',
      prefix: 'Your', suffix: 'to me a few years ago.',
      words: ['happened', 'of', 'reminded', 'similar', 'story', 'which', 'something', 'me'], note: null, source: '東洋大',
      answer: 'Your story reminded me of something similar which happened to me a few years ago.',
      explanation: '〈remind＋人＋of ～〉で「人に～を思い出させる」。somethingを形容詞similarが後ろから修飾し，さらに関係代名詞whichの節が続く。' },
    { id: 'c02', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 02', tagClass: 'tag-c',
      japanese: '彼女は急用ができて，昨日は福岡に出張することができなかった。［1語不要］',
      prefix: '', suffix: 'a business trip to Fukuoka yesterday.',
      words: ["couldn't", 'going', 'business', 'on', 'prevented', 'urgent', 'from', 'her'], note: '1語不要', source: '福岡大',
      answer: 'Urgent business prevented her from going on a business trip to Fukuoka yesterday.',
      explanation: '〈prevent＋人＋from doing〉で「人が…するのを妨げる」。無生物主語Urgent businessを立てるのでcouldn’tが不要。' },
    { id: 'c03', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 03', tagClass: 'tag-c',
      japanese: '', prefix: 'My younger brother', suffix: 'short.',
      words: ['cut', 'hair', 'having', 'his', 'hates'], note: null, source: '愛知大',
      translation: '私の弟は髪を短く切られるのをいやがる。',
      answer: 'My younger brother hates having his hair cut short.',
      explanation: '〈have＋物＋過去分詞〉で「物を…してもらう」。hatesの目的語に動名詞havingを置く。' },
    { id: 'c04', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 04', tagClass: 'tag-c',
      japanese: '', prefix: 'If the birthrate continues to fall in Japan, it will be difficult', suffix: '.',
      words: ['system', 'collapsing', 'the', 'stop', 'to', 'pension', 'from'], note: null, source: '芝浦工業大',
      translation: '日本で出生率が下がり続ければ，年金制度が崩壊するのを食い止めるのは難しくなるだろう。',
      answer: 'If the birthrate continues to fall in Japan, it will be difficult to stop the pension system from collapsing.',
      explanation: '〈stop＋O＋from doing〉で「Oが…するのを食い止める」。it will be difficult to doの真主語となる不定詞をつくる。' }
  ]
};

const EIGO_SENTENCES = [];

/* ── 問題集で丸をつけた問題（チェックしたら id を追加する） ── */
const MARKED_SET = {
  name: '丸をつけた問題',
  sub: '問題集でチェックした要復習の問題',
  ids: []
};
