// data.js — STEP 08 動詞の語法 ／ STEP 13 形容詞と副詞の語法（step で区別）
const QUIZ_DATA = {
  frames: [
    { step: 8, id: 'f063', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 063', tagClass: 'tag-f',
      question: 'I bought this T-shirt for my baby. It feels so ( ).',
      options: ['like soft', 'soft', 'softly', 'to be softly'], answer: 1, source: '近畿大',
      translation: '私は私の赤ちゃんのためにこのTシャツを買った。それは手触りがとても柔らかい。',
      explanation: 'feelは形容詞を補語にとり「…の感じがする」という意味を表すので，②softを選ぶ。' },
    { step: 8, id: 'f064', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 064', tagClass: 'tag-f',
      question: 'They ( ) the serious problem of rich families.',
      options: ['discussed of', 'discussed', 'discussed about', 'discussed with'], answer: 1, source: '神戸山手大',
      translation: '彼らは裕福な家庭の深刻な問題について議論した。',
      explanation: 'discussは「～について議論する」という意味の他動詞であり，目的語の前に前置詞は必要ないので，②discussedを選ぶ。' },
    { step: 8, id: 'f065', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 065', tagClass: 'tag-f',
      question: 'I cannot ( ) you how lucky I was to have a chance to see that painting.',
      options: ['tell', 'yell', 'speak', 'say'], answer: 0, source: '星薬科大',
      translation: 'その絵を見る機会があって私がいかに幸運だったかあなたに伝えきれない。',
      explanation: '空所のあとにyouとhowが導く節という2つの目的語が続いていることに着目する。tell A Bで「AにBを話す」の意味を表すので，①tellを選ぶ。②yell，③speak，④sayは目的語を2つとることはできないので，誤り。' },
    { step: 8, id: 'f066', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 066', tagClass: 'tag-f',
      question: 'Will you please explain ( ) once again?',
      options: ['the point us', 'us the point', 'the point to us', 'us about the point'], answer: 2, source: '東京工芸大',
      translation: 'もう1度要点を私たちに説明してくださいませんか。',
      explanation: 'explain A to Bで「AのことをBに説明する」という意味になるので，③the point to usを選ぶ。explainの直後に〈人〉はこないことに注意。' },
    { step: 8, id: 'f067', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 067', tagClass: 'tag-f',
      question: 'He ( ) on the sofa and quickly fell asleep.',
      options: ['lay', 'lied', 'lain', 'laid'], answer: 0, source: '茨城キリスト教大',
      translation: '彼はソファに横になるとすぐに眠った。',
      explanation: '「横になる」という意味の自動詞lieの過去形①layを選ぶ。lie–lay–lain' },
    { step: 8, id: 'f068', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 068', tagClass: 'tag-f',
      question: 'Drinking and smoking will ( ) you great harm.',
      options: ['have', 'be', 'help', 'do'], answer: 3, source: 'つくば国際大',
      translation: '飲酒と喫煙はあなたに多大な害を及ぼすだろう。',
      explanation: 'do O harmで「Oに害を及ぼす」という意味を表すので，④doを選ぶ。' },
    { step: 8, id: 'f069', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 069', tagClass: 'tag-f',
      question: 'Smoking robbed him ( ) his health.',
      options: ['to', 'of', 'with', 'for'], answer: 1, source: '亜細亜大',
      translation: '喫煙は彼から健康を奪った。',
      explanation: 'rob A of Bで「AからBを奪う」という意味を表すので，②ofを選ぶ。' },
    { step: 8, id: 'f070', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 070', tagClass: 'tag-f',
      question: 'The story that John told us reminded me ( ) another painful experience.',
      options: ['with', 'of', 'to', 'from'], answer: 1, source: '杏林大',
      translation: 'ジョンが私たちに語った話は，私に別の苦しかった経験を思い出させた。',
      explanation: 'remind A of Bで「AにBを思い出させる」という意味を表すので，②ofを選ぶ。' },
    { step: 8, id: 'f071', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 071', tagClass: 'tag-f',
      question: 'The horrible snowstorm discouraged us ( ) out.',
      options: ['from go', 'to go', 'from going', 'to going'], answer: 2, source: '南山大',
      translation: '大変ひどい吹雪のせいで，私たちは出かける気がなくなった。',
      explanation: 'discourage O from doingで「Oが…するのを思いとどまらせる」という意味を表すので，③from goingを選ぶ。' },
    { step: 8, id: 'f072', type: 'choice', section: 'frames', sectionName: 'FRAME', label: 'FRAME 072', tagClass: 'tag-f',
      question: 'She had her hair ( ) for the dance.',
      options: ['to be cut', 'cutting', 'to cut', 'cut'], answer: 3, source: '法政大',
      translation: '彼女はダンスパーティーのために髪を切ってもらった。',
      explanation: 'hadは使役動詞。〈have＋O＋done〉で「Oを…してもらう，される」という意味を表すので，④cutを選ぶ。' }
  ],
  exA: [
    { step: 8, id: 'a01', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 01', tagClass: 'tag-a',
      question: "Don't climb up that ladder! It doesn't look ( ).",
      options: ['safe', 'safely', 'in safety', 'dangerously'], answer: 0, source: '福岡大',
      translation: 'そのはしごを上がってはだめだ！ 安全なようには見えない。',
      explanation: 'lookは形容詞を補語にとり「…に見える」という意味を表すので，①safeを選ぶ。' },
    { step: 8, id: 'a02', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 02', tagClass: 'tag-a',
      question: 'Two students are going to ( ) the topic.',
      options: ['discuss', 'discuss about', 'discuss on', 'discuss of'], answer: 0, source: '摂南大',
      translation: '2人の生徒がその話題について議論する予定だ。',
      explanation: 'discussは「～について議論する」という意味の他動詞であり，目的語の前に前置詞は必要ないので，①discussを選ぶ。' },
    { step: 8, id: 'a03', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 03', tagClass: 'tag-a',
      question: 'Kevin and Julie got ( ) in Hawaii.',
      options: ['marry', 'marriage', 'marrying', 'married'], answer: 3, source: '南山大',
      translation: 'ケビンとジュリーはハワイで結婚した。',
      explanation: 'marryはbe[get] married (to ～)の形で「(～と)結婚する」という意味を表すので，④marriedを選ぶ。' },
    { step: 8, id: 'a04', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 04', tagClass: 'tag-a',
      question: 'When did you ( ) that university?',
      options: ['graduate', 'graduate at', 'graduate from', 'graduate of'], answer: 2, source: '神奈川大',
      translation: 'あなたはあの大学をいつ卒業したのですか。',
      explanation: 'graduateは自動詞であり，graduate from ～の形で「～を卒業する」という意味を表すので，③graduate fromを選ぶ。' },
    { step: 8, id: 'a05', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 05', tagClass: 'tag-a',
      question: 'The first typhoon is ( ) the Philippines right now.',
      options: ['approaching', 'coming', 'going', 'nearness'], answer: 0, source: '東京工芸大',
      translation: '台風1号は現在フィリピンに接近中だ。',
      explanation: '空所の直後にthe Philippinesという目的語が続いているので，他動詞が入る。approachは「～に近づく」という意味の他動詞なので，①approachingを選ぶ。' },
    { step: 8, id: 'a06', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 06', tagClass: 'tag-a',
      question: 'She can ( ) me at this number.',
      options: ['talk', 'take', 'arrive', 'reach'], answer: 3, source: '駒澤大',
      translation: '彼女はこの番号で私と連絡をとることができる。',
      explanation: '空所の直後にmeという目的語が続いているので，他動詞が入る。「～と連絡をとる」という意味を表す他動詞④reachを選ぶ。' },
    { step: 8, id: 'a07', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 07', tagClass: 'tag-a',
      question: 'He ( ) the room saying hello.',
      options: ['appeared', 'came', 'emerged', 'entered'], answer: 3, source: '日本大',
      translation: '彼はあいさつをしながら部屋に入った。',
      explanation: '空所の直後にthe roomという目的語が続いているので，他動詞が入る。enterは「～に入る」という意味の他動詞なので，④enteredを選ぶ。' },
    { step: 8, id: 'a08', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 08', tagClass: 'tag-a',
      question: 'He was so worn out that he just ( ) down and slept.',
      options: ['had lain', 'laid', 'lay', 'lied'], answer: 2, source: '北里大',
      translation: '彼はすっかり疲れ切っていたので，ただもう横になって眠った。',
      explanation: 'lie downで「横たわる」という意味を表すので，自動詞lieの過去形③layを選ぶ。' },
    { step: 8, id: 'a09', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 09', tagClass: 'tag-a',
      question: 'These books ( ) young people great harm.',
      options: ['do', 'make', 'have', 'give'], answer: 0, source: '関西学院大',
      translation: 'これらの本は若者に多大な害を及ぼす。',
      explanation: 'do O harmで「Oに害を及ぼす」という意味を表すので，①doを選ぶ。' },
    { step: 8, id: 'a10', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 10', tagClass: 'tag-a',
      question: 'The pilot ( ) the landing was delayed.',
      options: ['explained to us what', 'explained us why', 'explained to us why', 'explained us of why'], answer: 2, source: '同志社大',
      translation: 'パイロットはなぜ着陸が遅れたのかを私たちに説明した。',
      explanation: 'explain to O that [why] ... で「that [why]以下のことをOに説明する」という意味になるので，③explained to us whyを選ぶ。空所のあとはS(the landing)＋V(was delayed)と完全な文になっているので，whatを用いた①は不可。' },
    { step: 8, id: 'a11', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 11', tagClass: 'tag-a',
      question: 'Would you please ( ) me where the subway station is?',
      options: ['say', 'explain', 'tell', 'speak'], answer: 2, source: '名城大',
      translation: '地下鉄の駅がどこか私に教えていただけませんか。',
      explanation: '空所のあとにmeとwhereが導く節という2つの目的語が続いていることに着目する。tell A Bで「AにBを話す」の意味を表すので，③tellを選ぶ。' },
    { step: 8, id: 'a12', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 12', tagClass: 'tag-a',
      question: 'The newspaper ( ) it was going to rain.',
      options: ['said', 'spoke', 'talked', 'told'], answer: 0, source: '関西学院大',
      translation: '新聞には雨になるだろうと書いてあった。',
      explanation: '空所のあとに〈S＋V〉の節が続いているので，that節を目的語にとり，「(本などに)…と書いてある」という意味を表すsayの過去形①saidを選ぶ。ここではthatが省略されている。' },
    { step: 8, id: 'a13', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 13', tagClass: 'tag-a',
      question: 'Jennifer ( ) her own work experience in India.',
      options: ['spoke', 'talked about', 'said', 'told to'], answer: 1, source: '甲南大',
      translation: 'ジェニファーは自分のインドでの仕事の経験について話した。',
      explanation: '空所のあとにher own work experience in Indiaという目的語が続いていることに着目。talk about ～で「～について話す」という意味になるので，②talked aboutを選ぶ。' },
    { step: 8, id: 'a14', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 14', tagClass: 'tag-a',
      question: 'Sitting there like that, you ( ) me of my mother.',
      options: ['remind', 'remember', 'recollect', 'recall'], answer: 0, source: '摂南大',
      translation: 'そんなふうにそこに座っていると，あなたは私に母を思い出させる。',
      explanation: 'remind A of Bで「AにBを思い出させる／気づかせる」という意味を表すので，①remindを選ぶ。②remember，③recollect，④recallはこの形をとらないので不可。' },
    { step: 8, id: 'a15', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 15', tagClass: 'tag-a',
      question: 'Kate ( ) of all the money she had with her.',
      options: ['robbed', 'was robbed', 'deprived', 'had deprived'], answer: 1, source: '関西学院大',
      translation: 'ケイトは持っていたお金をすべて盗まれた。',
      explanation: 'rob A of Bで「AからBを奪う」という意味を表す。ここではAを主語とした受動態になるように，②was robbedを選ぶ。' },
    { step: 8, id: 'a16', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 16', tagClass: 'tag-a',
      question: "My parents are trying to ( ) me from moving to London, but I'm planning to go anyway.",
      options: ['discourage', 'recall', 'observe', 'relieve'], answer: 0, source: '獨協大',
      translation: '私の両親は私がロンドンに移り住むのを思いとどまらせようとしているが，私はそれでもやはり行くつもりだ。',
      explanation: 'discourage O from doingで「Oが…するのを思いとどまらせる」という意味を表すので，①discourageを選ぶ。②recall，③observe，④relieveはこの形をとらないので不可。' },
    { step: 8, id: 'a17', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 17', tagClass: 'tag-a',
      question: 'A new law ( ) people from drinking in the park.',
      options: ['permits', 'prohibits', 'refuses', 'exhibits'], answer: 1, source: '甲南大',
      translation: '新しい法律は人々が公園で飲酒することを禁止している。',
      explanation: 'prohibit O from doingで「Oが…するのを禁じる」という意味を表すので，②prohibitsを選ぶ。①permits，③refuses，④exhibitsはこの形をとらないので不可。' },
    { step: 8, id: 'a18', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 18', tagClass: 'tag-a',
      question: 'Prior research has shown that the key to building muscles ( ) in a healthy diet.',
      options: ['lays', 'lies', 'lying', 'will lay'], answer: 1, source: '立命館大',
      translation: '先の研究は，筋肉を増強する秘けつは健康的な食事にあることを示している。',
      explanation: 'lie in ～で「～にある」という意味を表すので，②liesを選ぶ。' },
    { step: 8, id: 'a19', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 19', tagClass: 'tag-a',
      question: 'Because of the noise, Tom had to ( ) his voice to be heard.',
      options: ['rise', 'stand', 'heighten', 'raise'], answer: 3, source: '芝浦工業大',
      translation: '騒音のせいで，トムは自分の言うことを聞いてもらうために声を張り上げねばならなかった。',
      explanation: '空所の直後にhis voiceという目的語が続いているので，他動詞が入る。「(声など)を張り上げる」という意味を持つ他動詞④raiseを選ぶ。' },
    { step: 8, id: 'a20', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 20', tagClass: 'tag-a',
      question: 'The number of cases of the disease continued to ( ).',
      options: ['raise', 'rise', 'raising', 'rising'], answer: 1, source: '亜細亜大',
      translation: 'その病気の症例数は増え続けた。',
      explanation: '目的語がなく，toに続く不定詞なので自動詞②riseを選ぶ。自動詞riseと他動詞raiseで活用と意味が紛らわしいので，注意が必要。' },
    { step: 8, id: 'a21', type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 21', tagClass: 'tag-a',
      question: 'He had his bicycle ( ) in front of that convenience store.',
      options: ['stealing', 'steal', 'stolen', 'be stolen'], answer: 2, source: '追手門学院大',
      translation: '彼はあのコンビニの前で自転車を盗まれた。',
      explanation: 'hadは使役動詞。〈have＋O＋done〉で「Oを…してもらう，される」という意味を表すので，③stolenを選ぶ。' },
    { id: 's13a11', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 11', tagClass: 'tag-a',
      question: 'Because of ( ) weather conditions, Shizuoka Prefecture has an advantage in the production of fruits and vegetables.',
      options: ['favorite', 'favorable', 'favor', 'favorably'], answer: 1, source: '早稲田大',
      translation: 'よい気象条件のおかげで，静岡県は果物や野菜の生産に有利である。',
      explanation: 'weather conditions「気象条件」を修飾するので，②favorable「好都合な」を選ぶ。①favorite「お気に入りの」は文の内容に合わないので不可。' },
    { id: 's13a12', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 12', tagClass: 'tag-a',
      question: "We always try to be ( ) of each other's opinions, no matter how much we disagree.",
      options: ['respective', 'respectful', 'respecting', 'respectable'], answer: 1, source: '学習院大',
      translation: '私たちは，どんなに意見が合わなくても，お互いの意見を常に尊重しようとしている。',
      explanation: '文の内容より，respectful of ～「～に敬意を払う」となるように，②respectfulを選ぶ。①respective「それぞれの／各自の」，④respectable「ちゃんとした／立派な」は文の内容に合わないので不可。' },
    { id: 's13a13', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 13', tagClass: 'tag-a',
      question: 'She is so ( ) that she cried for days when her pet rabbit died.',
      options: ['impressed', 'impressive', 'sensible', 'sensitive'], answer: 3, source: 'センター試験',
      translation: '彼女はとても傷つきやすいので，ペットのウサギが死んだときには何日も泣いた。',
      explanation: '文の内容より，④sensitive「傷つきやすい」を選ぶ。①impressed「感動した」，②impressive「印象的な／すばらしい」，③sensible「分別のある／賢明な」は文の内容に合わないので不可。' },
    { id: 's13a14', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 14', tagClass: 'tag-a',
      question: '( ) activities are those approved of by society because they are considered to be fair and honest.',
      options: ['Respect', 'Respectable', 'Respecting', 'Respective'], answer: 1, source: 'センター試験',
      translation: '立派な活動とは，公正で正直なものと考えられているという理由で，社会に認められた活動のことである。',
      explanation: '文の内容より，②Respectable「ちゃんとした／立派な」を選ぶ。④Respective「それぞれの／各自の」は文の内容に合わないので不可。' },
    { id: 's13a15', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 15', tagClass: 'tag-a',
      question: "I'm terribly sorry, but I'm ( ) to help you in any way.",
      options: ['unable', 'impossible', 'incapable', 'enable'], answer: 0, source: '九州産業大',
      translation: '本当に申し訳ありませんが，どうしてもあなたを助けることができません。',
      explanation: '直後のto helpに着目する。be unable to doで「…することができない」という意味を表すので，①unableを選ぶ。②impossibleは人を主語にとることができないので不可。③incapableはbe incapable of doingの形で「…することができない」を表すので不可。' },
    { id: 's13a16', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 16', tagClass: 'tag-a',
      question: 'Tokyo has a ( ) population.',
      options: ['large', 'much', 'high', 'expensive'], answer: 0, source: '城西大',
      translation: '東京は人口が多い。',
      explanation: 'population「人口」の「多い⇔少ない」はlarge↔smallで表すため，①largeを選ぶ。' },
    { id: 's13a17', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 17', tagClass: 'tag-a',
      question: "I can't believe how ( ) their prices are!",
      options: ['light', 'expensive', 'high', 'few'], answer: 2, source: '山梨大',
      translation: 'それらの値段はなんと高いことか，私には信じられない。',
      explanation: 'price「値段」の「高い⇔安い」はhigh↔lowで表すため，③highを選ぶ。' },
    { id: 's13a18', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 18', tagClass: 'tag-a',
      question: 'There was ( ) audience at the theater.',
      options: ['much', 'many', 'a large', 'lot'], answer: 2, source: '愛知産業大',
      translation: '映画館にはたくさんの観客がいた。',
      explanation: 'audience「観客」の「多い⇔少ない」はlarge↔smallで表すため，③a largeを選ぶ。a large audienceと冠詞がつくことにも注意する。' },
    { id: 's13a19', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 19', tagClass: 'tag-a',
      question: 'Is that project worth ( ) at a great expense to the taxpayer?',
      options: ['launch', 'launching', 'launched', 'to launch'], answer: 1, source: '東京理科大',
      translation: 'そのプロジェクトは納税者に多大な負担をかけてまで着手する価値があるのですか。',
      explanation: 'S is worth doingで「Sは…する価値がある」という意味になるので，②launchingを選ぶ。' },
    { id: 's13a20', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 20', tagClass: 'tag-a',
      question: 'Could you call me back if ( ) not convenient for you to talk now?',
      options: ['we are', 'it is', 'you are', 'I am'], answer: 1, source: 'センター試験',
      translation: '今話すのに都合がよくなければ，あとで電話をいただけますか。',
      explanation: 'convenient「都合のよい」は人を主語にすることができない。「(人)にとって都合がよい」というときはconvenient for＋人で表す。to talkを真主語とする形式主語のitを用いた形の②it isを選ぶ。' },
    { id: 's13a21', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 21', tagClass: 'tag-a',
      question: 'Hardly ( ) of my friends smoke.',
      options: ['any', 'not', 'some', 'a few'], answer: 0, source: '駒澤大',
      translation: '私の友人はほとんどみんな，タバコを吸わない。',
      explanation: 'hardly any of ～で「～のほとんどがない」という意味を表すので，①anyを選ぶ。' },
    { id: 's13a22', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 22', tagClass: 'tag-a',
      question: 'Scarcely ( ) in the office knew what they were supposed to do when the alarm went off.',
      options: ['everyone', 'no one', 'anyone', 'all of them'], answer: 2, source: '学習院大',
      translation: '警報機が鳴り出したとき，オフィスのほとんどだれも，何をすることになっているかわかっていなかった。',
      explanation: 'scarcelyは「ほとんど…ない」という意味を表す準否定語。scarcely anyoneで「ほとんどだれも…ない」という意味になるので，③anyoneを選ぶ。' },
    { id: 's13a23', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 23', tagClass: 'tag-a',
      question: 'I was ( ) involved in a car accident. I narrowly escaped being run over.',
      options: ['mostly', 'most', 'almost', 'more'], answer: 2, source: '玉川大',
      translation: '私はもう少しで自動車事故に巻き込まれるところだった。ひかれるのをかろうじて免れた。',
      explanation: 'was involvedを修飾するので，「ほとんど／もう少しで」という意味を表す副詞③almostを選ぶ。①mostly「たいていは」，②most「最も」，④more「さらに」は，文の内容に合わないので不可。' },
    { id: 's13a24', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 24', tagClass: 'tag-a',
      question: 'Linda arrived at the office ( ) because there was a traffic jam.',
      options: ['late', 'lately', 'slow', 'slowly'], answer: 0, source: '金沢工業大',
      translation: '交通渋滞があったので，リンダは会社に着くのが遅れた。',
      explanation: 'arrived「着いた」を修飾するので，「遅く」という意味を表す副詞①lateを選ぶ。②lately「最近」，③slow「ゆっくりと」，④slowly「ゆっくりと」は，文の内容に合わないので不可。' },
    { id: 's13a25', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 25', tagClass: 'tag-a',
      question: 'If you want to get a high score on the test, you should study very ( ).',
      options: ['hardly', 'many', 'hard', 'almost'], answer: 2, source: '松本歯科大',
      translation: 'テストで高得点をとりたいのなら，一生懸命勉強するべきだ。',
      explanation: 'should study「勉強するべきだ」を修飾するので，「熱心に」という意味を表す副詞③hardを選ぶ。①hardly「ほとんど…ない」，④almost「ほとんど」は，文の内容に合わないので不可。' },
    { id: 's13a26', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 26', tagClass: 'tag-a',
      question: 'Polluted air drifts all over. It even rises ( ) above the Earth.',
      options: ['high', 'highly', 'height', 'tall'], answer: 0, source: '広島工業大',
      translation: '汚染された大気は至る所に漂う。それは地上高くにまで上昇する。',
      explanation: 'rises「上昇する」を修飾するので，「高く」という意味を表す副詞①highを選ぶ。②highly「非常に」は文の内容に合わないので不可。' },
    { id: 's13a27', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 27', tagClass: 'tag-a',
      question: "Has Mark been here ( )? I haven't seen him around.",
      options: ['fast', 'faster', 'lately', 'at late'], answer: 2, source: '金沢工業大',
      translation: 'マークは最近ここに来たかい？ 彼を見かけないのだけど。',
      explanation: '文の内容より，「最近」という意味を表す副詞③latelyを選ぶ。①fast「速く」，②faster「より速く」は，文の内容に合わないので不可。' },
    { id: 's13a28', step: 13, type: 'choice', section: 'exA', sectionName: 'Exercise A', label: 'Ex. A 28', tagClass: 'tag-a',
      question: 'You look tired. You should go ( ) early today.',
      options: ['home', 'to home', 'to house', 'house'], answer: 0, source: '東海大',
      translation: '疲れているようだね。今日は早く帰宅すべきだよ。',
      explanation: 'goを修飾するので，「家へ」という意味を表す副詞①homeを選ぶ。②，③，④は名詞のhomeやhouseに冠詞または所有格などが必要なので，不可。' }
  ],
  exB: [
    { step: 8, id: 'b01', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 01', tagClass: 'tag-b',
      question: '①After ②attending the meeting yesterday, he ③seriously ④talked the issue.',
      options: ['①', '②', '③', '④'], answer: 3, source: '明海大',
      spans: ['After', 'attending', 'seriously', 'talked'],
      correction: '④ talked → talked about（discussed も可）', corrected: 'After attending the meeting yesterday, he seriously talked about the issue.',
      translation: '昨日の会議に出席したあと，彼はその問題について真剣に話した。',
      explanation: 'talkは自動詞なので，直後に目的語をとることができない。「～について話した」という意味になるように，④talkedをtalked aboutにする。' },
    { step: 8, id: 'b02', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 02', tagClass: 'tag-b',
      question: 'The rays ①from the sun penetrate the atmosphere, ②while the ③greenhouse gases prevent heat ④to escape into space.',
      options: ['①', '②', '③', '④'], answer: 3, source: '関西学院大',
      spans: ['from', 'while', 'greenhouse gases', 'to escape'],
      correction: '④ to escape → from escaping', corrected: 'The rays from the sun penetrate the atmosphere, while the greenhouse gases prevent heat from escaping into space.',
      translation: '太陽からの光線は大気中を通り抜けるが，一方，温室効果ガスは熱が宇宙空間に流出するのを妨げる。',
      explanation: 'prevent O from doingで「Oが…するのを妨げる」という意味を表すので，④to escapeはfrom escapingにする。' },
    { step: 8, id: 'b03', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 03', tagClass: 'tag-b',
      question: 'The author is going to ①discuss to the implications of mobile Internet access for libraries, ②which would allow innovation in ③their ④services.',
      options: ['①', '②', '③', '④'], answer: 0, source: '明治学院大',
      spans: ['discuss to', 'which', 'their', 'services'],
      correction: '① discuss to → discuss', corrected: 'The author is going to discuss the implications of mobile Internet access for libraries, which would allow innovation in their services.',
      translation: '筆者は図書館におけるインターネットモバイル接続がもつ意味合いについてこれから論じるが，それは図書館のサービスに革新をもたらすだろうものである。',
      explanation: 'discussは「～について議論する」という意味の他動詞であり，目的語の前に前置詞は必要ないので，①discuss toはdiscussにする。' },
    { step: 8, id: 'b04', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 04', tagClass: 'tag-b',
      question: 'When we visited ①her office for a regular check-up, Dr. Dixon told my mom ②to go to the hospital ③to have her stomach ④examine.',
      options: ['①', '②', '③', '④'], answer: 3, source: '杏林大',
      spans: ['her office', 'to go', 'to have', 'examine'],
      correction: '④ examine → examined', corrected: 'When we visited her office for a regular check-up, Dr. Dixon told my mom to go to the hospital to have her stomach examined.',
      translation: '私たちが定期検診のために診療所を訪れたとき，ディクソン先生は私の母に，胃を検査してもらうために病院へ行くようにと言った。',
      explanation: 'haveは使役動詞。〈have＋O＋done〉で「Oを…してもらう，される」という意味を表すので，④examineはexaminedにする。' },
    { step: 8, id: 'b05', type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 05', tagClass: 'tag-b',
      question: '①Owing to the appearance of competitors in the neighborhood, we will have to ②give up our plan to ③rise the price by twenty ④percent.',
      options: ['①', '②', '③', '④'], answer: 2, source: '福岡大',
      spans: ['Owing to', 'give up', 'rise', 'percent'],
      correction: '③ rise → raise', corrected: 'Owing to the appearance of competitors in the neighborhood, we will have to give up our plan to raise the price by twenty percent.',
      translation: '近所に競合相手が出現したために，私たちは価格を20パーセント上げる計画を取りやめなければならないだろう。',
      explanation: 'riseは自動詞で，直後に目的語をとることはできないので，③riseは「～を上げる」という意味を表す他動詞raiseにする。' },
    { id: 's13b01', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 01', tagClass: 'tag-b',
      question: '①I also surprised that ②Japan received aid from UNICEF ③after World War II.',
      options: ['①', '②', '③'], answer: 0, source: '上智大',
      spans: ['I also surprised', 'Japan received aid', 'after World War II'],
      correction: '① I also surprised → I was also surprised', corrected: 'I was also surprised that Japan received aid from UNICEF after World War II.',
      translation: '日本が第二次世界大戦後ユニセフから援助を受けていたことにも，私は驚いた。',
      explanation: 'surpriseは「(人)を驚かせる」という意味の他動詞なので，人を主語としたときには受動態にする。過去分詞surprisedは形容詞化して「(人が)驚いて」という意味を表す。したがって，①I also surprisedはI was also surprisedにする。' },
    { id: 's13b02', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 02', tagClass: 'tag-b',
      question: 'She ①told me ②that her training program was both ③exciting and ④frustrated.',
      options: ['①', '②', '③', '④'], answer: 3, source: '東洋大',
      spans: ['told', 'that', 'exciting', 'frustrated'],
      correction: '④ frustrated → frustrating', corrected: 'She told me that her training program was both exciting and frustrating.',
      translation: '彼女は私に，自分のトレーニングプログラムは，わくわくするものであるのと同時にイライラするものでもあるのだと言った。',
      explanation: '④frustratedは「(人が)欲求不満の，イライラしている」という意味の形容詞で，主語のher training programに合わないのでfrustrating「(物事が)イライラする」にする。' },
    { id: 's13b03', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 03', tagClass: 'tag-b',
      question: 'If I ①am accepted by this college, I ②will ③definitely study ④hardly.',
      options: ['①', '②', '③', '④'], answer: 3, source: '甲南大',
      spans: ['am accepted', 'will', 'definitely', 'hardly'],
      correction: '④ hardly → hard', corrected: 'If I am accepted by this college, I will definitely study hard.',
      translation: 'もし私がこの大学に受け入れられたら，絶対に一生懸命勉強する。',
      explanation: '④hardlyは「ほとんど…ない」という意味を表す副詞なので，「熱心に」という意味を表す副詞hardにする。' },
    { id: 's13b04', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 04', tagClass: 'tag-b',
      question: 'She is ①eager to know ②whether you experienced something ③amazed ④during your travels in Europe.',
      options: ['①', '②', '③', '④'], answer: 2, source: '福岡大',
      spans: ['eager', 'whether', 'amazed', 'during'],
      correction: '③ amazed → amazing', corrected: 'She is eager to know whether you experienced something amazing during your travels in Europe.',
      translation: '彼女はあなたがヨーロッパ旅行中にびっくりするようなことを何か経験したかどうか知りたがっている。',
      explanation: '③amazedは「(人が)驚いた，びっくりした」を表す。ここではsomethingを修飾するので，「(物事が)驚くべき，びっくりするような」を表すamazingにする。' },
    { id: 's13b05', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 05', tagClass: 'tag-b',
      question: '①All of those present ②appeared to be ③very ④boring by his speech.',
      options: ['①', '②', '③', '④'], answer: 3, source: '学習院大',
      spans: ['All of', 'appeared', 'very', 'boring'],
      correction: '④ boring → bored', corrected: 'All of those present appeared to be very bored by his speech.',
      translation: '出席していた人全員，彼のスピーチにはとても退屈しているようだった。',
      explanation: '④boringは「(物事が)つまらない，退屈な」を表し，主語All of those present「出席していた人全員」に合わないので，bored「(人が)退屈した」にする。' },
    { id: 's13b06', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 06', tagClass: 'tag-b',
      question: 'Bill gets ①few exercise and is not very fit. His doctor often tells him ②to be on his guard ③against putting on too ④much weight.',
      options: ['①', '②', '③', '④'], answer: 0, source: '京都外国語大',
      spans: ['few', 'to be', 'against', 'much'],
      correction: '① few → little', corrected: 'Bill gets little exercise and is not very fit. His doctor often tells him to be on his guard against putting on too much weight.',
      translation: 'ビルはほとんど運動をせず，あまり調子がよくない。彼のお医者さんは彼に，太りすぎに注意するようにしばしば言う。',
      explanation: 'exercise「運動」は数えられない名詞なので，①few「(数が)ほとんど…ない」はlittle「(量が)ほとんど…ない」にする。' },
    { id: 's13b07', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 07', tagClass: 'tag-b',
      question: "The terms 'liberal' and 'conservative' ①have changed so much ②over time that it is now worth ③to pause to reflect ④on them.",
      options: ['①', '②', '③', '④'], answer: 2, source: '上智大',
      spans: ['have changed', 'over time', 'to pause', 'on'],
      correction: '③ to pause → pausing', corrected: "The terms 'liberal' and 'conservative' have changed so much over time that it is now worth pausing to reflect on them.",
      translation: '「liberal(自由主義の)」や「conservative(保守主義の)」という言葉は時間が経つにつれてずいぶん変化してきたので，今あらためてそれらの言葉について考えてみる価値がある。',
      explanation: 'it is worth doingで「…するだけの価値がある」という意味になるので，③to pauseはpausingとする。' },
    { id: 's13b08', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 08', tagClass: 'tag-b',
      question: 'Having ①little money ②with me, ③I am impossible ④to afford such a costly bag.',
      options: ['①', '②', '③', '④'], answer: 2, source: '甲南大',
      spans: ['little', 'with', 'I am', 'to afford'],
      correction: '③ I am → I find it [it is]', corrected: 'Having little money with me, I find it impossible to afford such a costly bag.',
      translation: 'ほとんどお金を持っていないので，そんな高価なかばんを買うのは不可能だ。',
      explanation: 'impossible「不可能な」は人を主語にすることができないので，③I amはI find itまたはit isとする。【補足】it is にすると，分詞構文 Having little money with me の意味上の主語（I）と文の主語（it）がずれる（懸垂分詞）ので，I find it のほうが確実。' },
    { id: 's13b09', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 09', tagClass: 'tag-b',
      question: 'My friends and I ①stayed behind after school to ②study ③until it was time for us to go ④to home.',
      options: ['①', '②', '③', '④'], answer: 3, source: '南山大',
      spans: ['stayed', 'study', 'until', 'to home'],
      correction: '④ to home → home', corrected: 'My friends and I stayed behind after school to study until it was time for us to go home.',
      translation: '友人たちと私は放課後も居残って，私たちが下校する時間になるまで勉強した。',
      explanation: 'homeは「家へ」という意味を表す副詞として用いられるので，④to homeはhomeとする。' },
    { id: 's13b10', step: 13, type: 'exB', section: 'exB', sectionName: 'Exercise B', label: 'Ex. B 10', tagClass: 'tag-b',
      question: 'After ①many discussion and comparison, the couple ②who ③had been living in the town for ten years agreed ④to buy the house.',
      options: ['①', '②', '③', '④'], answer: 0, source: '明治学院大',
      spans: ['many', 'who', 'had been living', 'to buy'],
      correction: '① many → much [a lot of]', corrected: 'After much discussion and comparison, the couple who had been living in the town for ten years agreed to buy the house.',
      translation: 'じっくり議論と比較をしたあとに，10年間その町に住み続けてきた夫婦はその家を買うことに同意した。',
      explanation: 'discussionとcomparisonはここでは単数形になっており，数えられない名詞として扱われている。数えられない名詞をmanyで修飾することはできないので，①manyはmuchまたはa lot ofにする。' }
  ],
  exC: [
    { step: 8, id: 'c01', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 01', tagClass: 'tag-c',
      japanese: 'あなたの話を聞いて，数年前に私にも同じようなことがあったのを思い出した。',
      prefix: 'Your', suffix: 'to me a few years ago.',
      words: ['happened', 'of', 'reminded', 'similar', 'story', 'which', 'something', 'me'], note: null, source: '東洋大',
      answer: 'Your story reminded me of something similar which happened to me a few years ago.',
      explanation: '「あなたの話は私に～を思い出させた」と考える。remind A of Bが「AにBを思い出させる」という意味なので，Your story reminded me ofとする。「同じようなこと」はsomething similarとし，関係代名詞whichを用いた節which happened to me ...を続ける。' },
    { step: 8, id: 'c02', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 02', tagClass: 'tag-c',
      japanese: '彼女は急用ができて，昨日は福岡に出張することができなかった。［1語不要］',
      prefix: '', suffix: 'a business trip to Fukuoka yesterday.',
      words: ["couldn't", 'going', 'business', 'on', 'prevented', 'urgent', 'from', 'her'], note: '1語不要', source: '福岡大',
      answer: 'Urgent business prevented her from going on a business trip to Fukuoka yesterday.',
      explanation: '「急用は彼女が～に出張することを妨げた」と考える。prevent O from doingで「Oが…するのを妨げる」という意味を表すので，Urgent business prevented her from goingとつなげる。「出張する」はgo on a business trip。（couldn’tが不要）' },
    { step: 8, id: 'c03', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 03', tagClass: 'tag-c',
      japanese: '', prefix: 'My younger brother', suffix: 'short.',
      words: ['cut', 'hair', 'having', 'his', 'hates'], note: null, source: '愛知大',
      translation: '私の弟は髪を短く切ってもらうのをいやがる。',
      answer: 'My younger brother hates having his hair cut short.',
      explanation: 'hate doingで「…するのをいやがる」という意味になるので，まずhates havingとする。〈have＋O＋done〉で「Oを…してもらう，される」という意味を表すので，having his hair cutとつなげる。' },
    { step: 8, id: 'c04', type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 04', tagClass: 'tag-c',
      japanese: '', prefix: 'If the birthrate continues to fall in Japan, it will be difficult', suffix: '.',
      words: ['system', 'collapsing', 'the', 'stop', 'to', 'pension', 'from'], note: null, source: '芝浦工業大',
      translation: 'もし日本で出生率が下がり続けたら，年金制度が崩壊するのを止めるのは難しいだろう。',
      answer: 'If the birthrate continues to fall in Japan, it will be difficult to stop the pension system from collapsing.',
      explanation: '形式主語itがあるので，真主語の不定詞の部分を組み立てる。stop O from doingで「Oが…するのを妨げる」という意味を表すので，to stop the pension system from collapsingとつなげればよい。' },
    { id: 's13c01', step: 13, type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 01', tagClass: 'tag-c',
      japanese: '都合がよければ，火曜日の11時に来てください。',
      prefix: "Please come at 11 o'clock on Tuesday", suffix: '.',
      words: ['it', 'for', 'you', 'convenient', 'if', 'is'], note: null, source: '埼玉医科大',
      answer: "Please come at 11 o'clock on Tuesday if it is convenient for you.",
      explanation: 'convenient「都合のよい」は人を主語にすることができない。「(人)にとって都合がよい」というときはconvenient for＋人で表すので，if it is convenient for youとする。' },
    { id: 's13c02', step: 13, type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 02', tagClass: 'tag-c',
      japanese: '建物の中に入るたびに私たちの手を洗わなければならなかった。',
      prefix: 'It was', suffix: 'the building.',
      words: ['each', 'hands', 'inside', 'necessary', 'our', 'time', 'to', 'wash', 'we', 'went'], note: null, source: '京都女子大',
      answer: 'It was necessary to wash our hands each time we went inside the building.',
      explanation: 'necessary「必要な」は人を主語にすることができない。Itを形式主語として用い，真主語をto不定詞で表す。まず「私たちの手を洗うことが必要だった」と考え，It was necessary to wash our handsとする。「…するたびに」はeach time ...で表せる。「～の中に入る」はwe went inside ～で表す。' },
    { id: 's13c03', step: 13, type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 03', tagClass: 'tag-c',
      japanese: 'その国には小学校のない村はほとんどない。',
      prefix: 'In the country there is', suffix: 'school.',
      words: ['without', 'elementary', 'hardly', 'any', 'its', 'village'], note: null, source: '和光大',
      answer: 'In the country there is hardly any village without its elementary school.',
      explanation: '「ほとんど～がない」はhardly any ～で表すので，まずthere is hardly any villageとし，villageを修飾するwithout its elementary schoolをこのあとに続ける。' },
    { id: 's13c04', step: 13, type: 'exC', section: 'exC', sectionName: 'Exercise C', label: 'Ex. C 04', tagClass: 'tag-c',
      japanese: '', prefix: 'In this small town there are', suffix: 'the mayor personally.',
      words: ['not', 'know', 'who', 'do', 'people', 'few'], note: null, source: '獨協大',
      translation: 'この小さな町には，市長を個人的に知らない人はほとんどいない。',
      answer: 'In this small town there are few people who do not know the mayor personally.',
      explanation: 'fewは「(数が)ほとんどない」という意味で数えられる名詞を修飾するので，there areにfew peopleを続ける。これを修飾するwho節のwho do not know the mayor personallyをそのあとに置く。' }
  ]
};

const EIGO_SENTENCES = [];

/* ── 問題集で丸をつけた問題（チェックしたら id を追加する） ── */
const MARKED_SET = {
  name: '丸をつけた問題',
  sub: '問題集でチェックした要復習の問題',
  ids: []
};
