// dict.js — 長押しで出す英単語の意味（問題に出てくる語はすべて登録する）
// キーは小文字。活用形は「原形の◯◯形」を添える。
const WORD_DICT = {
  'a': '〔冠詞〕1つの，ある',
  'about': '〔前〕～について　〔副〕およそ',
  'access': '〔名〕接続，利用（する権利）',
  'after': '〔前・接〕～のあとで',
  'again': '〔副〕再び，もう一度',
  'ago': '〔副〕（今から）～前に',
  'all': '〔形・代〕すべての，全部',
  'allow': '〔動〕～を可能にする，許す',
  'and': '〔接〕～と…，そして',
  'another': '〔形・代〕もう1つの，別の',
  'anyway': '〔副〕とにかく，それでもやはり',
  'appearance': '〔名〕出現，外見',
  'appeared': '〔動〕appear の過去形　現れた，～に見えた（自動詞）',
  'approach': '〔動〕～に近づく（他動詞）',
  'approaching': '〔動〕approach の -ing形　～に近づいている',
  'are': '〔動〕be の現在形（主語が複数・you）　～である，いる',
  'arrive': '〔動〕到着する（自動詞：arrive at / in ～）',
  'asleep': '〔形〕眠って（fall asleep：眠りに落ちる）',
  'at': '〔前〕～で，～に（地点・時点）',
  'atmosphere': '〔名〕大気，雰囲気',
  'attending': '〔動〕attend の -ing形　～に出席すること',
  'author': '〔名〕著者，筆者',
  'baby': '〔名〕赤ちゃん',
  'be': '〔動〕～である，いる（原形）',
  'because': '〔接〕～なので（because of ～：～のために）',
  'bicycle': '〔名〕自転車',
  'birthrate': '〔名〕出生率',
  'books': '〔名〕book（本）の複数形',
  'bought': '〔動〕buy の過去形・過去分詞　買った',
  'brother': '〔名〕兄弟（younger brother：弟）',
  'building': '〔動〕build の -ing形　～を築くこと，増強すること',
  'business': '〔名〕用事，仕事（urgent business：急用／business trip：出張）',
  'but': '〔接〕しかし',
  'by': '〔前〕～だけ（差），～によって，～のそばに',
  'came': '〔動〕come の過去形　来た（自動詞）',
  'can': '〔助〕～できる',
  'cannot': '〔助〕～できない',
  'cases': '〔名〕case の複数形　症例，場合',
  'chance': '〔名〕機会，見込み',
  'check-up': '〔名〕健康診断（regular check-up：定期検診）',
  'climb': '〔動〕～に登る（climb up ～）',
  'collapsing': '〔動〕collapse の -ing形　崩壊すること',
  'coming': '〔動〕come の -ing形　来ている（自動詞）',
  'competitors': '〔名〕competitor の複数形　競争相手，競合店',
  'continued': '〔動〕continue の過去形　続けた，続いた',
  'continues': '〔動〕continue の3単現　続ける，続く',
  'convenience': '〔名〕便利（convenience store：コンビニ）',
  "couldn't": '〔助〕could not の短縮形　～できなかった',
  'cut': '〔動〕～を切る（cut-cut-cut：過去形・過去分詞も cut）',
  'cutting': '〔動〕cut の -ing形　切っている',
  'dance': '〔名〕ダンスパーティー，ダンス',
  'dangerously': '〔副〕危険なほど，危険に',
  'delayed': '〔動〕delay の過去分詞　遅れた（be delayed：遅れる）',
  'deprived': '〔動〕deprive の過去形・過去分詞　奪った（deprive A of B：AからBを奪う）',
  'did': '〔動・助〕do の過去形',
  'diet': '〔名〕（日常の）食事，食生活',
  'difficult': '〔形〕難しい',
  'discourage': '〔動〕～の気をくじく（discourage O from doing：Oに…するのを思いとどまらせる）',
  'discouraged': '〔動〕discourage の過去形　～する気をなくさせた',
  'discuss': '〔動〕～について議論する（他動詞：前置詞は不要）',
  'discussed': '〔動〕discuss の過去形・過去分詞　～について議論した',
  'disease': '〔名〕病気',
  'dixon': '〔人名〕ディクソン',
  'do': '〔動〕～をする，（害・利益）を与える（do O harm：Oに害を与える）',
  "doesn't": '〔助〕does not の短縮形',
  'doing': '〔動〕do の -ing形（文法用語では「動名詞」の意）',
  "don't": '〔助〕do not の短縮形　（命令文で）～するな',
  'done': '〔動〕do の過去分詞（文法用語では「過去分詞」の意）',
  'down': '〔副〕下へ（lie down：横になる）',
  'dr': '〔略〕Doctor　～先生，～博士',
  'drinking': '〔名・動〕飲酒，飲むこと',
  'emerged': '〔動〕emerge の過去形　現れた，出てきた（自動詞）',
  'enter': '〔動〕～に入る（他動詞：前置詞は不要）',
  'entered': '〔動〕enter の過去形　～に入った',
  'escape': '〔動〕逃げる，流出する',
  'escaping': '〔動〕escape の -ing形　逃げること，流出すること',
  'examine': '〔動〕～を検査する，調べる',
  'examined': '〔動〕examine の過去形・過去分詞　検査された',
  'exhibits': '〔動〕exhibit の3単現　～を展示する',
  'experience': '〔名〕経験',
  'explain': '〔動〕～を説明する（explain A to B：AをBに説明する）',
  'explained': '〔動〕explain の過去形　説明した',
  'fall': '〔動〕下がる，落ちる',
  'families': '〔名〕family（家族，家庭）の複数形',
  'feel': '〔動〕～の感じがする（feel＋形容詞）',
  'feels': '〔動〕feel の3単現　～の感じがする，手触りが～だ',
  'fell': '〔動〕fall の過去形（fell asleep：眠りに落ちた）',
  'few': '〔形〕少数の（a few：少しの，2，3の）',
  'first': '〔形〕最初の（the first typhoon：台風1号）',
  'for': '〔前〕～のために，～の間',
  'from': '〔前〕～から（prevent / stop O from doing：Oが…するのを妨げる）',
  'front': '〔名〕前（in front of ～：～の前で）',
  'fukuoka': '〔地名〕福岡',
  'gases': '〔名〕gas の複数形　ガス，気体',
  'get': '〔動〕～になる，～を得る',
  'give': '〔動〕～を与える（give up：あきらめる）',
  'go': '〔動〕行く（go out：外出する）',
  'going': '〔動〕go の -ing形（be going to do：…する予定だ）',
  'got': '〔動〕get の過去形（got married：結婚した）',
  'graduate': '〔動〕卒業する（自動詞：graduate from ～）',
  'great': '〔形〕大きな，多大な，すばらしい',
  'greenhouse': '〔名〕温室（greenhouse gases：温室効果ガス）',
  'had': '〔動〕have の過去形・過去分詞（had to do：…しなければならなかった）',
  'hair': '〔名〕髪',
  'happened': '〔動〕happen の過去形　起こった（happen to ～：～に起こる）',
  'harm': '〔名〕害，損害',
  'has': '〔動〕have の3単現',
  'hate': '〔動〕～をひどく嫌う（hate doing：…するのをいやがる）',
  'hates': '〔動〕hate の3単現　～をいやがる',
  'have': '〔動〕～を持つ／〔使役〕have O done：Oを…してもらう・される',
  'having': '〔動〕have の -ing形',
  'hawaii': '〔地名〕ハワイ',
  'he': '〔代〕彼は',
  'health': '〔名〕健康',
  'healthy': '〔形〕健康的な，健康な',
  'heard': '〔動〕hear の過去形・過去分詞　聞こえた（be heard：聞いてもらう）',
  'heat': '〔名〕熱',
  'heighten': '〔動〕～を高める（程度・感情などを）',
  'hello': '〔間〕こんにちは（say hello：あいさつする）',
  'help': '〔動〕～を助ける，手伝う',
  'her': '〔代〕彼女の，彼女を',
  'him': '〔代〕彼を，彼に',
  'his': '〔代〕彼の',
  'horrible': '〔形〕ひどい，恐ろしい',
  'hospital': '〔名〕病院',
  'how': '〔副〕どれほど，どのように',
  'i': '〔代〕私は',
  "i'm": '〔略〕I am の短縮形',
  'if': '〔接〕もし～ならば',
  'implications': '〔名〕implication の複数形　（予想される）影響，意味合い',
  'in': '〔前〕～の中で，～に',
  'india': '〔地名〕インド',
  'innovation': '〔名〕革新，新しい工夫',
  'internet': '〔名〕インターネット',
  'into': '〔前〕～の中へ',
  'is': '〔動〕be の3単現　～である，いる',
  'issue': '〔名〕問題，論点',
  'it': '〔代〕それ（形式主語・天候の it もある）',
  'japan': '〔地名〕日本',
  'jennifer': '〔人名〕ジェニファー',
  'john': '〔人名〕ジョン',
  'julie': '〔人名〕ジュリー',
  'just': '〔副〕ただ，ちょうど',
  'kate': '〔人名〕ケイト',
  'kevin': '〔人名〕ケビン',
  'key': '〔名〕秘けつ，鍵（the key to ～：～の秘けつ）',
  'ladder': '〔名〕はしご',
  'laid': '〔動〕lay（～を置く・横たえる）の過去形・過去分詞',
  'lain': '〔動〕lie（横になる）の過去分詞',
  'landing': '〔名〕着陸',
  'law': '〔名〕法律',
  'lay': '〔動〕① lie（横になる）の過去形　② ～を置く，横たえる（他動詞・原形）',
  'lays': '〔動〕lay（～を置く）の3単現',
  'libraries': '〔名〕library（図書館）の複数形',
  'lie': '〔動〕① 横になる，ある（lie-lay-lain）　② うそをつく（lie-lied-lied）',
  'lied': '〔動〕lie（うそをつく）の過去形・過去分詞',
  'lies': '〔動〕lie の3単現　ある，横たわる（lie in ～：～にある）',
  'like': '〔前〕～のような　〔動〕～が好きだ',
  'london': '〔地名〕ロンドン',
  'look': '〔動〕～に見える（look＋形容詞）',
  'lucky': '〔形〕幸運な',
  'lying': '〔動〕lie の -ing形　横になっている，うそをついている',
  'make': '〔動〕～を作る，～させる',
  'marriage': '〔名〕結婚',
  'married': '〔動・形〕marry の過去分詞　結婚した（get married：結婚する）',
  'marry': '〔動〕～と結婚する（他動詞）',
  'marrying': '〔動〕marry の -ing形',
  'me': '〔代〕私を，私に',
  'meeting': '〔名〕会議，会合',
  'mobile': '〔形〕モバイルの，移動式の',
  'mom': '〔名〕お母さん',
  'money': '〔名〕お金',
  'mother': '〔名〕母',
  'moving': '〔動〕move の -ing形　引っ越すこと，移り住むこと',
  'muscles': '〔名〕muscle の複数形　筋肉',
  'my': '〔代〕私の',
  'nearness': '〔名〕近いこと，接近',
  'neighborhood': '〔名〕近所，地域',
  'new': '〔形〕新しい',
  'newspaper': '〔名〕新聞',
  'noise': '〔名〕騒音',
  'now': '〔副〕今（right now：今まさに）',
  'number': '〔名〕数，番号（the number of ～：～の数）',
  'observe': '〔動〕～を観察する，（規則など）を守る',
  'of': '〔前〕～の（rob / remind A of B などでも使う）',
  'office': '〔名〕診療所，事務所',
  'on': '〔前〕～の上に，～に乗って（go on a trip：旅に出る）',
  'once': '〔副〕一度（once again：もう一度）',
  'our': '〔代〕私たちの',
  'out': '〔副〕外へ（go out：外出する／worn out：疲れ切った）',
  'owing': '〔形〕owing to ～：～のために，～が原因で',
  'own': '〔形〕自分自身の',
  'painful': '〔形〕つらい，痛い',
  'painting': '〔名〕絵，絵画',
  'parents': '〔名〕parent の複数形　両親',
  'park': '〔名〕公園',
  'penetrate': '〔動〕～を通り抜ける，貫く',
  'pension': '〔名〕年金（pension system：年金制度）',
  'people': '〔名〕人々',
  'percent': '〔名〕パーセント',
  'permits': '〔動〕permit の3単現　～を許可する',
  'philippines': '〔地名〕フィリピン（the Philippines）',
  'pilot': '〔名〕パイロット，操縦士',
  'plan': '〔名〕計画',
  'planning': '〔動〕plan の -ing形（be planning to do：…するつもりだ）',
  'please': '〔副〕どうぞ，どうか',
  'point': '〔名〕要点，論点',
  'prevent': '〔動〕～を妨げる（prevent O from doing：Oが…するのを妨げる）',
  'prevented': '〔動〕prevent の過去形　妨げた',
  'price': '〔名〕価格，値段',
  'prior': '〔形〕前の，先の',
  'problem': '〔名〕問題',
  'prohibit': '〔動〕～を禁じる（prohibit O from doing：Oが…するのを禁じる）',
  'prohibits': '〔動〕prohibit の3単現　禁じる',
  'quickly': '〔副〕すぐに，素早く',
  'rain': '〔動〕雨が降る　〔名〕雨',
  'raise': '〔動〕～を上げる（他動詞：raise-raised-raised）',
  'raising': '〔動〕raise の -ing形',
  'rays': '〔名〕ray の複数形　光線',
  'reach': '〔動〕～に連絡をとる，～に着く（他動詞）',
  'recall': '〔動〕～を思い出す，呼び戻す',
  'recollect': '〔動〕～を思い出す',
  'refuses': '〔動〕refuse の3単現　～を断る，拒む',
  'regular': '〔形〕定期的な，通常の',
  'relieve': '〔動〕～を和らげる，安心させる',
  'remember': '〔動〕～を覚えている，思い出す',
  'remind': '〔動〕～に思い出させる（remind A of B：AにBを思い出させる）',
  'reminded': '〔動〕remind の過去形　思い出させた',
  'research': '〔名〕研究，調査',
  'rich': '〔形〕裕福な',
  'right': '〔副〕ちょうど（right now：今まさに）　〔形〕正しい',
  'rise': '〔動〕上がる，増える（自動詞：rise-rose-risen）',
  'rising': '〔動〕rise の -ing形',
  'rob': '〔動〕～から奪う（rob A of B：AからBを奪う）',
  'robbed': '〔動〕rob の過去形・過去分詞　奪った（be robbed of ～：～を奪われる）',
  'room': '〔名〕部屋',
  'safe': '〔形〕安全な',
  'safely': '〔副〕安全に',
  'safety': '〔名〕安全（in safety：安全に）',
  'said': '〔動〕say の過去形・過去分詞　言った，（新聞などに）書いてあった',
  'say': '〔動〕～と言う，（本などに）～と書いてある',
  'saying': '〔動〕say の -ing形（saying hello：あいさつしながら）',
  'see': '〔動〕～を見る',
  'serious': '〔形〕深刻な，真剣な',
  'seriously': '〔副〕真剣に，深刻に',
  'services': '〔名〕service の複数形　サービス，業務',
  'she': '〔代〕彼女は',
  'short': '〔形・副〕短い，短く',
  'shown': '〔動〕show の過去分詞　示した',
  'similar': '〔形〕似た，同じような',
  'sitting': '〔動〕sit の -ing形　座っている',
  'slept': '〔動〕sleep の過去形・過去分詞　眠った',
  'smoking': '〔名・動〕喫煙，タバコを吸うこと',
  'snowstorm': '〔名〕吹雪',
  'so': '〔副〕とても，それほど（so ～ that …：とても～なので…）',
  'sofa': '〔名〕ソファ',
  'soft': '〔形〕柔らかい',
  'softly': '〔副〕柔らかく，静かに',
  'something': '〔代〕何か（something similar：何か似たこと）',
  'space': '〔名〕宇宙（空間），空間',
  'speak': '〔動〕話す（自動詞が中心：speak to ～／speak about ～）',
  'spoke': '〔動〕speak の過去形',
  'stand': '〔動〕立つ，～に耐える',
  'station': '〔名〕駅',
  'steal': '〔動〕～を盗む（steal-stole-stolen）',
  'stealing': '〔動〕steal の -ing形',
  'stolen': '〔動〕steal の過去分詞　盗まれた',
  'stomach': '〔名〕胃，おなか',
  'stop': '〔動〕～を止める（stop O from doing：Oが…するのを止める）',
  'store': '〔名〕店',
  'story': '〔名〕話，物語',
  'students': '〔名〕student の複数形　生徒，学生',
  'subway': '〔名〕地下鉄',
  'sun': '〔名〕太陽',
  'system': '〔名〕制度，システム',
  't-shirt': '〔名〕Tシャツ',
  'take': '〔動〕～を取る，連れて行く',
  'talk': '〔動〕話す（自動詞：talk about ～／talk to ～）',
  'talked': '〔動〕talk の過去形　話した（自動詞：talked about ～）',
  'tell': '〔動〕～に…を話す，伝える（tell A B）',
  'that': '〔代〕あれ，それ　〔接〕～ということ　〔関代〕～する（もの）',
  'the': '〔冠詞〕その',
  'their': '〔代〕彼らの，それらの',
  'there': '〔副〕そこで',
  'these': '〔形・代〕これらの',
  'they': '〔代〕彼らは',
  'this': '〔形・代〕この，これ',
  'to': '〔前〕～へ，～に　〔不定詞〕to do：…すること，…するために',
  'told': '〔動〕tell の過去形・過去分詞　話した，伝えた',
  'tom': '〔人名〕トム',
  'topic': '〔名〕話題，テーマ',
  'trip': '〔名〕旅行（business trip：出張）',
  'trying': '〔動〕try の -ing形（try to do：…しようとする）',
  'twenty': '〔数〕20',
  'two': '〔数〕2',
  'typhoon': '〔名〕台風',
  'university': '〔名〕大学',
  'up': '〔副〕上へ（climb up：登る／give up：あきらめる）',
  'urgent': '〔形〕緊急の（urgent business：急用）',
  'us': '〔代〕私たちを，私たちに',
  'visited': '〔動〕visit の過去形　訪れた',
  'voice': '〔名〕声（raise one\'s voice：声を張り上げる）',
  'was': '〔動〕be の過去形',
  'we': '〔代〕私たちは',
  'what': '〔代〕何，～すること（もの）',
  'when': '〔副〕いつ　〔接〕～するとき',
  'where': '〔副〕どこに',
  'which': '〔関代〕～する（もの）　〔代〕どれ',
  'while': '〔接〕一方で，～する間に',
  'why': '〔副〕なぜ',
  'will': '〔助〕～だろう，～するつもりだ',
  'with': '〔前〕～と一緒に，～を持って',
  'work': '〔名〕仕事',
  'worn': '〔動〕wear の過去分詞（worn out：疲れ切った）',
  'would': '〔助〕will の過去形　～だろう（Would you ～?：～していただけますか）',
  'years': '〔名〕year（年）の複数形',
  'yell': '〔動〕叫ぶ，怒鳴る',
  'yesterday': '〔副・名〕昨日',
  'you': '〔代〕あなた（たち）は，あなた（たち）を',
  'young': '〔形〕若い（young people：若者）',
  'younger': '〔形〕young の比較級（younger brother：弟）',
  'your': '〔代〕あなたの'
};

// 2語以上のまとまり（長押しした語を含む熟語があれば一緒に出す）
const PHRASE_DICT = {
  'a few': '少しの，2，3の',
  'because of': '～のために，～が原因で',
  'business trip': '出張',
  'climb up': '～を登る',
  'convenience store': 'コンビニエンスストア',
  'fell asleep': '眠りに落ちた（fall asleep）',
  'get married': '結婚する',
  'got married': '結婚した',
  'give up': '～をあきらめる，取りやめる',
  'go out': '外出する',
  'go on a business trip': '出張する',
  'going on': '（旅行などに）出かけること',
  'graduate from': '～を卒業する',
  'greenhouse gases': '温室効果ガス',
  'had to': '～しなければならなかった',
  'in front of': '～の前で',
  'lie down': '横になる',
  'lay down': '横になった（lie down の過去形）',
  'lie in': '～にある',
  'lies in': '～にある',
  'mobile internet access': 'モバイルインターネット接続',
  'once again': 'もう一度',
  'owing to': '～のために，～が原因で',
  'pension system': '年金制度',
  'prior research': '先行研究，これまでの研究',
  'regular check-up': '定期検診',
  'right now': '今まさに，ちょうど今',
  'say hello': 'あいさつする',
  'saying hello': 'あいさつしながら',
  'talk about': '～について話す',
  'talked about': '～について話した',
  'the number of': '～の数',
  'the key to': '～の秘けつ，～への鍵',
  'urgent business': '急用',
  'worn out': '疲れ切った',
  'young people': '若者',
  'younger brother': '弟',
  'do harm': '害を与える（do O harm：Oに害を与える）',
  'great harm': '多大な害',
  'with her': '身につけて（had with her：持っていた）'
};
